---
title: "Creating dataframes"
author: '3034081184'
date: "2024-03-22"
output: html_document
---


Load packages and data
```{r}
library(tidyverse)


# plots with Card#B removed, ask Anya what they are
regen <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/Regen_2023_ALL.csv"
regen <- read.csv(regen)
site <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/Site.csv"
site <- read.csv(site)
GIS_i <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/from_GIS.csv"
GIS_i <- read.csv(GIS_i)
clipGis <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/PossiblePlot.csv"
clipGis <- read.csv(clipGis)
internal <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/Internal.csv"
internal <- read.csv(internal)
basal <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/BasalArea.csv"
basal <- read.csv(basal)

```

Format plot data
```{r}
# Fill in blank species, NR = no regen
regen$Species <- sub("^$", "NR", regen$Species)
regen$Species <- sub("ACT", "NonCon", regen$Species)
regen$Species <- sub("AT", "NonCon", regen$Species)
regen$Species <- sub("SW", "Spruce", regen$Species)
regen$Species <- sub("SE", "Spruce", regen$Species)
regen$Species <- sub("SX", "Spruce", regen$Species)


# get rid of unnecessary columns
regen<- regen %>% 
  select(Card,Quandrant,Species,Notes,x0,x10,x30,x130) 

# new column for species by plot
regen$Plot_Sp <- paste(regen$Card, regen$Species, sep = "")

#new column for total of seedlings per wedge by species
regen<- regen%>% 
  mutate(total = rowSums(cbind(regen$x0,regen$x10,regen$x30,regen$x130),na.rm=TRUE))

#combine different wedges by height class

regen_only_total <- regen %>% 
  group_by(Card, Species, Plot_Sp) %>% 
  summarise(across(total, sum))

regen_only_x0 <- regen %>% 
  group_by(Plot_Sp) %>% 
  summarise(x0 = sum(x0, na.rm = TRUE))

regen_only_x10 <- regen %>% 
  group_by(Plot_Sp) %>% 
  summarise(x10 = sum(x10, na.rm = TRUE))

regen_only_x30 <- regen %>% 
  group_by(Plot_Sp) %>% 
  summarise(x30 = sum(x30, na.rm = TRUE))

regen_only_x130 <- regen %>% 
  group_by(Plot_Sp) %>% 
  summarise(x130 = sum(x130, na.rm = TRUE))

#combine into 1 data frame

regen_all <- full_join(regen_only_total, regen_only_x0, by = "Plot_Sp") %>% 
  full_join(regen_only_x10, by = "Plot_Sp") %>% 
  full_join(regen_only_x30, by = "Plot_Sp") %>%
  full_join(regen_only_x130, by = "Plot_Sp")

# now i want to have columns for each species
regen_all$FDI_total <- ifelse(regen_all$Species == "FDI", regen_all$total, 0)
regen_all$FDI_x0 <- ifelse(regen_all$Species == "FDI", regen_all$x0, 0)
regen_all$FDI_x10 <- ifelse(regen_all$Species == "FDI", regen_all$x10, 0)
regen_all$FDI_x30 <- ifelse(regen_all$Species == "FDI", regen_all$x30, 0)
regen_all$FDI_x130 <- ifelse(regen_all$Species == "FDI", regen_all$x130, 0)
regen_all$PLI_total <- ifelse(regen_all$Species == "PLI", regen_all$total, 0)
regen_all$PLI_x0 <- ifelse(regen_all$Species == "PLI", regen_all$x0, 0)
regen_all$PLI_x10 <- ifelse(regen_all$Species == "PLI", regen_all$x10, 0)
regen_all$PLI_x30 <- ifelse(regen_all$Species == "PLI", regen_all$x30, 0)
regen_all$PLI_x130 <- ifelse(regen_all$Species == "PLI", regen_all$x130, 0)
regen_all$NonCon_total <- ifelse(regen_all$Species == "NonCon", regen_all$total, 0)
regen_all$NonCon_x0 <- ifelse(regen_all$Species == "NonCon", regen_all$x0, 0)
regen_all$NonCon_x10 <- ifelse(regen_all$Species == "NonCon", regen_all$x10, 0)
regen_all$NonCon_x30 <- ifelse(regen_all$Species == "NonCon", regen_all$x30, 0)
regen_all$NonCon_x130 <- ifelse(regen_all$Species == "NonCon", regen_all$x130, 0)
regen_all$Spruce_total <- ifelse(regen_all$Species == "Spruce", regen_all$total, 0)
regen_all$Spruce_x0 <- ifelse(regen_all$Species == "Spruce", regen_all$x0, 0)
regen_all$Spruce_x10 <- ifelse(regen_all$Species == "Spruce", regen_all$x10, 0)
regen_all$Spruce_x30 <- ifelse(regen_all$Species == "Spruce", regen_all$x30, 0)
regen_all$Spruce_x130 <- ifelse(regen_all$Species == "Spruce", regen_all$x130, 0)
#regen_all$Conifer_total <- ifelse(regen_all$Species == grpl("Spruce", regen_all$total, 0)
#regen_all$Conifer_x0 <- ifelse(regen_all$Species == "Spruce", regen_all$x0, 0)
#regen_all$Conifer_x10 <- ifelse(regen_all$Species == "Spruce", regen_all$x10, 0)
#regen_all$Conifer_x30 <- ifelse(regen_all$Species == "Spruce", regen_all$x30, 0)
#regen_all$Conifer_x130 <- ifelse(regen_all$Species == "Spruce", regen_all$x130, 0)

#Need to make it for conifer but waiting until at lab


# remove NR rows for plots that have other species present
regen_all <- regen_all %>% 
  group_by(Card) %>% 
  mutate(has_nr = any(Species == "NR"), num_rows = n()) %>% 
  filter(num_rows == 1 | !(has_nr & Species == "NR")) %>% 
  select(-has_nr, -num_rows)


## Check if we removed the correct values
# look into plots that have counts larger than zero. Seems like there should have been a species recorded
#(plots 1505, 1529, 1567, 1647, 1739, 2318)
regen_retained <- regen_all %>% 
  group_by(Card) %>% 
  mutate(has_nr = any(Species == "NR"), num_rows = n()) %>% 
  filter(num_rows == 1 | !(has_nr & Species == "NR")) %>% 
  select(-has_nr, -num_rows)

## Create dataframe with removed rows
regen_removed <- regen_all %>%
  anti_join(regen_retained, by = c("Card", "Species"))

# combine rows for same plot
##Add conifer##
regen_combo <- regen_all %>%
  group_by(Card) %>%
  summarize(SpeciesAll = paste(Species, collapse = ", "),
            total_count = sum(total),
            total_tph = total_count*200,
            total_x0 = sum(x0),
            total_x10 = sum(x10),
            total_x30 = sum(x30),
            total_x130 = sum(x130),
            FDI_count = sum(FDI_total),
            FDI_tph = FDI_count*200,
            FDI_x0 = sum(FDI_x0),
            FDI_x10 = sum(FDI_x10),
            FDI_x30 = sum(FDI_x30),
            FDI_x130 = sum(FDI_x130),
            PLI_count = sum(PLI_total),
            PLI_tph = PLI_count*200,
            PLI_x0 = sum(PLI_x0),
            PLI_x10 = sum(PLI_x10),
            PLI_x30 = sum(PLI_x30),
            PLI_x130 = sum(PLI_x130),
            NonCon_count = sum(NonCon_total),
            NonCon_x0 = sum(NonCon_x0),
            NonCon_x10 = sum(NonCon_x10),
            NonCon_x30 = sum(NonCon_x30),
            NonCon_x130 = sum(NonCon_x130),
            Spruce_count = sum(Spruce_total),
            Spruce_x0 = sum(Spruce_x0),
            Spruce_x10 = sum(Spruce_x10),
            Spruce_x30 = sum(Spruce_x30),
            Spruce_x130 = sum(Spruce_x130)) %>% 
  ungroup()

# export dataframe
#write.csv(regen_combo, "C:/Users/nmac2000/Documents/regen project/Regen/Dataframes/MeasuredPlots.csv")
```

Clip GIS data to only potential plots and edit Aspect
```{r}
# add GIS data
regen$Card <- as.integer(regen$Card)
regen_copy <- regen #don't
regen_copy <- regen_copy %>% 
  rename(SampleSite_ID = Card)
clipped_plots <- semi_join(clipGis, regen_copy, "SampleSite_ID")
forgotten_plots <- anti_join(regen_copy, clipped_plots, "SampleSite_ID")

clipGIS1 <- clipGis %>% 
  select(SampleSite_ID)
forgotten_plots <- forgotten_plots %>% 
  select(SampleSite_ID)
clipGis <- full_join(clipGIS1,forgotten_plots, "SampleSite_ID")

GIS_i <- semi_join(GIS_i, clipGIS, "SampleSite_ID")
GIS_i$Card <- as.integer(GIS_i$SampleSite_ID)
regen_combo$Card <- as.integer(regen_combo$Card, na.rm=TRUE)

#Edit overstory species to our catergories
GIS_i$Species_1 <- sub("\\bSX\\b", "Spruce", GIS_i$Species_1)
GIS_i$Species_1 <- sub("\\bS\\b", "Spruce", GIS_i$Species_1)
GIS_i$Species_1 <- sub("\\bSE\\b", "Spruce", GIS_i$Species_1)
GIS_i$Species_1 <- sub("\\bPL\\b", "PLI", GIS_i$Species_1)
GIS_i$Species_1 <- sub("\\bFD\\b", "FDI", GIS_i$Species_1)
GIS_i$Species_1 <- sub("\\bPA\\b", "PLI", GIS_i$Species_1)



#Aspect

#northeast-to-southwest facing scale (Beers et al., 1996)
#Taspect = sin(aspect + 45) + 1



GIS_i$Beers_aspect <- sin(GIS_i$Aspect + 45) + 1


#Convert Aspect
assign_direction <- function(angle) {
  ifelse(is.na(angle), NA,  # Handle NA values
         ifelse(angle >= 315 || angle < 45, "N",
                ifelse(angle >= 45 && angle < 135, "E",
                       ifelse(angle >= 135 && angle < 225, "S", "W"))))
  }


# Apply the function to the data column
GIS_i$Azimuth <- sapply(GIS_i$Aspect, assign_direction)

write.csv(GIS_i, "C:/Users/nmac2000/Documents/regen project/Regen/Dataframes/GIS_fixed.csv")

```




Now it's plot data with GIS data
```{r}


regen_GIS <- left_join(regen_combo,GIS_i, by = "Card") %>% 
  ungroup()
write.csv(regen_GIS, "C:/Users/nmac2000/Documents/regen project/Regen/Dataframes/regen_GIS.csv")
```


Occurrence
```{r}
regen_binary <- regen_GIS %>% 
  mutate(total_count_bin = ifelse(total_count>0,1,0),
         total_x0_bin = ifelse(total_x0>0,1,0),
         total_x10_bin = ifelse(total_x10>0,1,0),
         total_x30_bin = ifelse(total_x30>0,1,0),
         total_x130_bin = ifelse(total_x130>0,1,0),
         FDI_count_bin = ifelse(FDI_count>0,1,0),
         FDI_x0_bin = ifelse(FDI_x0>0,1,0),
         FDI_x10_bin = ifelse(FDI_x10>0,1,0),
         FDI_x30_bin = ifelse(FDI_x30>0,1,0),
         FDI_x130_bin = ifelse(FDI_x130>0,1,0),
         PLI_count_bin = ifelse(PLI_count>0,1,0),
         PLI_x0_bin = ifelse(PLI_x0>0,1,0),
         PLI_x10_bin = ifelse(PLI_x10>0,1,0),
         PLI_x30_bin = ifelse(PLI_x30>0,1,0),
         PLI_x130_bin = ifelse(PLI_x130>0,1,0),
         NonCon_count_bin = ifelse(NonCon_count>0,1,0),
         NonCon_x0_bin = ifelse(NonCon_x0>0,1,0),
         NonCon_x10_bin = ifelse(NonCon_x10>0,1,0),
         NonCon_x30_bin = ifelse(NonCon_x30>0,1,0),
         NonCon_x130_bin = ifelse(NonCon_x130>0,1,0),
         Spruce_count_bin = ifelse(Spruce_count>0,1,0),
         Spruce_x0_bin = ifelse(Spruce_x0>0,1,0),
         Spruce_x10_bin = ifelse(Spruce_x10>0,1,0),
         Spruce_x30_bin = ifelse(Spruce_x30>0,1,0),
         Spruce_x130_bin = ifelse(Spruce_x130>0,1,0))

create_binary_columns <- function(data) {
  binary_cols <- c("total_count", "total_x0", "total_x10", "total_x30", "total_x130",
                   "FDI_count", "FDI_x0", "FDI_x10", "FDI_x30", "FDI_x130",
                   "PLI_count", "PLI_x0", "PLI_x10", "PLI_x30", "PLI_x130",
                   "NonCon_count", "NonCon_x0", "NonCon_x10", "NonCon_x30", "NonCon_x130",
                   "Spruce_count", "Spruce_x0", "Spruce_x10", "Spruce_x30", "Spruce_x130")
  
  for (col in binary_cols) {
    binary_col <- paste0(col, "_bin")
    data[[binary_col]] <- ifelse(data[[col]] > 0, 1, 0)
  }
  
  return(data)
}

regen_binary1 <- create_binary_columns(regen_GIS) %>% 
  select(Card, total_count_bin:Spruce_x130_bin)


regen_binary <- regen_binary %>% 
  select(Card, total_count_bin:Spruce_x130_bin)

library(testthat)
test_that("Test if data frames are same", {
  expect_equal(regen_binary,regen_binary1)
})

#combing binary with GIS data
bin_GIS <- left_join(regen_binary,GIS_i, by = "Card") %>% 
  ungroup()

write.csv(regen_binary, "C:/Users/nmac2000/Documents/regen project/Regen/Dataframes/regen_binary.csv")
write.csv(bin_GIS, "C:/Users/nmac2000/Documents/regen project/Regen/Dataframes/binary_GIS.csv")


```



