---
title: "FDI_structure"
author: "Nat"
date: "2024-08-08"
output: html_document
---

```{r}
#need to figure out data frames for everything and clean up code
bin_dis_GIS1 <- bin_dis_GIS %>%
  distinct(SampleSite_ID, .keep_all = T)
bin_dis_GIS1$BARC.x <- as.factor(bin_dis_GIS1$BARC.x)

```


Step 1
```{r}

logistic.null <- glm(FDI.f ~ 1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.null)

structure.FDIa <- glm(FDI.f ~ Distance ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDIa) 

structure.FDIb <- glm(FDI.f ~ years_since ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDIb)

structure.FDIc <- glm(FDI.f ~ CROWN_CLOSURE_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDIc) 

structure.FDId <- glm(FDI.f ~ PROJ_AGE_1_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDId) 

structure.FDIe <- glm(FDI.f ~ PROJ_HEIGHT_1_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDIe) 

structure.FDIf <- glm(FDI.f ~ DISTURBANCE_TYPE_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDIf) 

structure.FDIg <- glm(FDI.f ~ DISTANCE_TO_PERIMETER ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDIg) 

structure.FDIi <- glm(FDI.f ~ MEAN ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDIi)

structure.FDIj <- glm(FDI.f ~ FDI_percent ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDIj)

structure.FDIk <- glm(FDI.f ~ PATCHSIZE ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDIk)

structure.FDIl <- glm(FDI.f ~ BARC.x ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDIl)
lrtest(structure.FDIl, logistic.null)

lrtest(structure.FDIj, logistic.null)

```


# STep 2
```{r}
structure.FDI.3 <- glm(FDI.f ~ years_since + BARC.x ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDI.3)
lrtest(structure.FDI.3, structure.FDIb)

structure.FDI.3a <- glm(FDI.f ~ years_since + BARC.x + FDI_percent,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDI.3a)
lrtest(structure.FDI.3a, structure.FDI.3)

structure.FDI.3b <- glm(FDI.f ~ years_since + FDI_percent + PROJ_HEIGHT_1_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDI.3b)
lrtest(structure.FDI.3b, structure.FDI.3a)

structure.FDI.3c <- glm(FDI.f ~ years_since + BARC.x + FDI_percent + Distance,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDI.3c)
lrtest(structure.FDI.3c, structure.FDI.3a)

structure.FDI.3d <- glm(FDI.f ~ years_since + BARC.x +FDI_percent + Distance + PROJ_AGE_1_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDI.3d)
lrtest(structure.FDI.3d, structure.FDI.3c)

structure.FDI.3e <- glm(FDI.f ~ years_since + BARC.x +FDI_percent + Distance +
                          DISTANCE_TO_PERIMETER,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDI.3e)
lrtest(structure.FDI.3e, structure.FDI.3c) 

structure.FDI.3f <- glm(FDI.f ~  Distance + BARC.x + years_since + FDI_percent +
                          DISTURBANCE_TYPE_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDI.3f)
lrtest(structure.FDI.3f, structure.FDI.3c) #restrictions justified

structure.FDI.3g <- glm(FDI.f ~  Distance +years_since + BARC.x + FDI_percent,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDI.3g)
lrtest(structure.FDI.3g, structure.FDI.3c) #restrictions justified

structure.FDI.3h <- glm(FDI.f ~  Distance +years_since + BARC.x +FDI_percent +
                          PATCHSIZE,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDI.3h)
lrtest(structure.FDI.3h, structure.FDI.3g)

structure.FDI.3i <- glm(FDI.f ~   Distance +years_since + BARC.x +FDI_percent  + CROWN_CLOSURE_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDI.3i)
lrtest(structure.FDI.3i, structure.FDI.3g)

code
```

```{r}
structure.FDI.3i <- glm(FDI.f ~   Distance +years_since + BARC.x +FDI_percent ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDI.3i)


structure.FDI.3j <- glm(FDI.f ~   Distance +years_since + BARC.x +FDI_percent +FDI_percent*years_since ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.FDI.3j)
lrtest(structure.FDI.3i, structure.FDI.3j)
```

