---
title: "Models2"
author: "Nat"
date: "2024-08-07"
output: html_document
---

```{r}
climate$PLI.f <- as.factor(climate$PLI_count_bin)
climate$FDI.f <- as.factor(climate$FDI_count_bin)
```
# start modeling

```{r}
# Hot and Dry
climate.FDI.null <- glm(FDI.f ~ 1,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.null)

climate.FDI.a <- glm(FDI.f ~ MCMT,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.a)
lrtest(climate.FDI.a, climate.FDI.null)

climate.FDI.b <- glm(FDI.f ~ MWMT,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.b)
lrtest(climate.FDI.b, climate.FDI.null)

climate.FDI.c <- glm(FDI.f ~ Tmax_sm,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.c)
lrtest(climate.FDI.c, climate.FDI.null)

climate.FDI.d <- glm(FDI.f ~ MAP,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.d)
lrtest(climate.FDI.d, climate.FDI.null)

climate.FDI.e <- glm(FDI.f ~ PAS,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.e)
lrtest(climate.FDI.e, climate.FDI.null)

climate.FDI.f <- glm(FDI.f ~ PPT_sm,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.f)
lrtest(climate.FDI.f, climate.FDI.null)

climate.FDI.g <- glm(FDI.f ~ CMI_sm,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.g)
lrtest(climate.FDI.g, climate.FDI.null)

climate.FDI.h <- glm(FDI.f ~ AHM,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.h)
lrtest(climate.FDI.h, climate.FDI.null)

climate.FDI.i <- glm(FDI.f ~ SHM,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.i)
lrtest(climate.FDI.i, climate.FDI.null)
```

```{r}
# Cool and Wet Anomalies
climate.FDI.null <- glm(FDI.f ~ 1,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.null)

climate.FDI.1a <- glm(FDI.f ~ cool.wet.anomalies.MCMT,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.1a)
lrtest(climate.FDI.1a, climate.FDI.null)

climate.FDI.1b <- glm(FDI.f ~ cool.wet.anomalies.MWMT,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.1b)
lrtest(climate.FDI.1b, climate.FDI.null)

climate.FDI.1c <- glm(FDI.f ~ cool.wet.anomalies.Tmax_sm,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.1c)
lrtest(climate.FDI.1c, climate.FDI.null)

climate.FDI.1d <- glm(FDI.f ~ cool.wet.anomalies.MAP,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.1d)
lrtest(climate.FDI.1d, climate.FDI.null)

climate.FDI.1e <- glm(FDI.f ~ cool.wet.anomalies.PAS,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.1e)
lrtest(climate.FDI.1e, climate.FDI.null)

climate.FDI.1f <- glm(FDI.f ~ cool.wet.anomalies.PPT_sm,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.1f)
lrtest(climate.FDI.1f, climate.FDI.null)

climate.FDI.1g <- glm(FDI.f ~ cool.wet.anomalies.CMI_sm,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.1g)
lrtest(climate.FDI.1g, climate.FDI.null)

climate.FDI.1h <- glm(FDI.f ~ cool.wet.anomalies.AHM,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.1h)
lrtest(climate.FDI.1h, climate.FDI.null)

climate.FDI.1i <- glm(FDI.f ~ cool.wet.anomalies.SHM,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.1i)
lrtest(climate.FDI.1i, climate.FDI.null)


```
```{r}
climate.FDI.2a <- glm(FDI.f ~ years_since + MCMT,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.2a)
lrtest(climate.FDI.2a, climate.FDI.a)

climate.FDI.2b <- glm(FDI.f ~ years_since + MCMT + MWMT,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.2b)
lrtest(climate.FDI.2a, climate.FDI.2b)

climate.FDI.2c <- glm(FDI.f ~ years_since + MCMT + cool.wet.anomalies.MCMT ,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.2c)
lrtest(climate.FDI.2c, climate.FDI.2b)

climate.FDI.2d <- glm(FDI.f ~ years_since + MCMT + PAS,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.2d)
lrtest(climate.FDI.2d, climate.FDI.2a)


climate.FDI.2e <- glm(FDI.f ~ years_since + MCMT + PAS + CMI_sm + years_since*MCMT,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.2e)
lrtest(climate.FDI.2f, climate.FDI.2e)

climate.FDI.2f <- glm(FDI.f ~ years_since + MCMT + PAS + CMI_sm,
                       family = binomial(link="logit"), data=climate)
summary(climate.FDI.2f)
lrtest(climate.FDI.2f, climate.FDI.2e)

```


```{r}
climate.FDI.3 <- glm(FDI.f ~ NFFD_sp,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.3)

climate.FDI.3a <- glm(FDI.f ~ years_since + MCMT + PAS + NFFD_sp,
                        family = binomial(link="logit"), data=climate)
summary(climate.FDI.3a)
```
# IDF sub-model

```{r}
climate.IDF <- climate %>% 
  filter(BEC_Zone == "IDF")
```



```{r}
# Hot and Dry
climate.FDI.IDF.null <- glm(FDI.f ~ 1,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.null)

climate.FDI.IDF.a <- glm(FDI.f ~ MCMT,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.a)
lrtest(climate.FDI.IDF.a, climate.FDI.IDF.null)

climate.FDI.IDF.b <- glm(FDI.f ~ MWMT,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.b)
lrtest(climate.FDI.IDF.b, climate.FDI.IDF.null)

climate.FDI.IDF.c <- glm(FDI.f ~ Tmax_sm,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.c)
lrtest(climate.FDI.IDF.c, climate.FDI.IDF.null)

climate.FDI.IDF.d <- glm(FDI.f ~ MAP,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.d)
lrtest(climate.FDI.IDF.d, climate.FDI.IDF.null)

climate.FDI.IDF.e <- glm(FDI.f ~ PAS,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.e)
lrtest(climate.FDI.IDF.e, climate.FDI.IDF.null)

climate.FDI.IDF.f <- glm(FDI.f ~ PPT_sm,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.f)
lrtest(climate.FDI.IDF.f, climate.FDI.IDF.null)

climate.FDI.IDF.g <- glm(FDI.f ~ CMI_sm,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.g)
lrtest(climate.FDI.IDF.g, climate.FDI.IDF.null)

climate.FDI.IDF.h <- glm(FDI.f ~ AHM,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.h)
lrtest(climate.FDI.IDF.h, climate.FDI.IDF.null)

climate.FDI.IDF.i <- glm(FDI.f ~ SHM,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.i)
lrtest(climate.FDI.IDF.i, climate.FDI.IDF.null)
```
```{r}
# Cool and wet
climate.FDI.IDF.null <- glm(FDI.f ~ 1,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.null)

climate.FDI.IDF.a <- glm(FDI.f ~ MCMT_min,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.a)
lrtest(climate.FDI.IDF.a, climate.FDI.IDF.null)

climate.FDI.IDF.b <- glm(FDI.f ~ MWMT_min,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.b)
lrtest(climate.FDI.IDF.b, climate.FDI.IDF.null)

climate.FDI.IDF.c <- glm(FDI.f ~ Tmax_sm_min,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.c)
lrtest(climate.FDI.IDF.c, climate.FDI.IDF.null)

climate.FDI.IDF.d <- glm(FDI.f ~ MAP_max,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.d)
lrtest(climate.FDI.IDF.d, climate.FDI.IDF.null)

climate.FDI.IDF.e <- glm(FDI.f ~ PAS_max,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.e)
lrtest(climate.FDI.IDF.e, climate.FDI.IDF.null)

climate.FDI.IDF.f <- glm(FDI.f ~ PPT_sm_max,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.f)
lrtest(climate.FDI.IDF.f, climate.FDI.IDF.null)

climate.FDI.IDF.g <- glm(FDI.f ~ CMI_sm_max,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.g)
lrtest(climate.FDI.IDF.g, climate.FDI.IDF.null)

climate.FDI.IDF.h <- glm(FDI.f ~ AHM_min,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.h)
lrtest(climate.FDI.IDF.h, climate.FDI.IDF.null)

climate.FDI.IDF.i <- glm(FDI.f ~ SHM_min,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.i)
lrtest(climate.FDI.IDF.i, climate.FDI.IDF.null)
```

```{r}
# Cool and Wet Anomalies
climate.FDI.IDF.null <- glm(FDI.f ~ 1,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.null)

climate.FDI.IDF.1a <- glm(FDI.f ~ cool.wet.anomalies.MCMT,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.1a)
lrtest(climate.FDI.IDF.1a, climate.FDI.IDF.null)

climate.FDI.IDF.1b <- glm(FDI.f ~ cool.wet.anomalies.MWMT,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.1b)
lrtest(climate.FDI.IDF.1b, climate.FDI.IDF.null)

climate.FDI.IDF.1c <- glm(FDI.f ~ cool.wet.anomalies.Tmax_sm,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.1c)
lrtest(climate.FDI.IDF.1c, climate.FDI.IDF.null)

climate.FDI.IDF.1d <- glm(FDI.f ~ cool.wet.anomalies.MAP,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.1d)
lrtest(climate.FDI.IDF.1d, climate.FDI.IDF.null)

climate.FDI.IDF.1e <- glm(FDI.f ~ cool.wet.anomalies.PAS,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.1e)
lrtest(climate.FDI.IDF.1e, climate.FDI.IDF.null)

climate.FDI.IDF.1f <- glm(FDI.f ~ cool.wet.anomalies.PPT_sm,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.1f)
lrtest(climate.FDI.IDF.1f, climate.FDI.IDF.null)

climate.FDI.IDF.1g <- glm(FDI.f ~ cool.wet.anomalies.CMI_sm,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.1g)
lrtest(climate.FDI.IDF.1g, climate.FDI.IDF.null)

climate.FDI.IDF.1h <- glm(FDI.f ~ cool.wet.anomalies.AHM,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.1h)
lrtest(climate.FDI.IDF.1h, climate.FDI.IDF.null)

climate.FDI.IDF.1i <- glm(FDI.f ~ cool.wet.anomalies.SHM,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.1i)
lrtest(climate.FDI.IDF.1i, climate.FDI.IDF.null)


```
```{r}
climate.FDI.IDF.2a <- glm(FDI.f ~ years_since ,
                        family = binomial(link="logit"), data=climate.IDF)
summary(climate.FDI.IDF.2a)
lrtest(climate.FDI.IDF.a, climate.FDI.IDF.2a)
```

