---
title: "Models2"
author: "Nat"
date: "2024-08-07"
output: html_document
---

```{r}
climate$PLI.f <- as.factor(climate$PLI_count_bin)
climate$FDI.f <- as.factor(climate$FDI_count_bin)
```
# start modeling

```{r}
# Hot and Dry
climate.PLI.null <- glm(PLI.f ~ 1,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.null)

climate.PLI.a <- glm(PLI.f ~ MCMT,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.a)
lrtest(climate.PLI.a, climate.PLI.null)

climate.PLI.b <- glm(PLI.f ~ MWMT,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.b)
lrtest(climate.PLI.b, climate.PLI.null)

climate.PLI.c <- glm(PLI.f ~ Tmax_sm,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.c)
lrtest(climate.PLI.c, climate.PLI.null)

climate.PLI.d <- glm(PLI.f ~ MAP,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.d)
lrtest(climate.PLI.d, climate.PLI.null)

climate.PLI.e <- glm(PLI.f ~ PAS,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.e)
lrtest(climate.PLI.e, climate.PLI.null)

climate.PLI.f <- glm(PLI.f ~ PPT_sm,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.f)
lrtest(climate.PLI.f, climate.PLI.null)

climate.PLI.g <- glm(PLI.f ~ CMI_sm,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.g)
lrtest(climate.PLI.g, climate.PLI.null)

climate.PLI.h <- glm(PLI.f ~ AHM,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.h)
lrtest(climate.PLI.h, climate.PLI.null)

climate.PLI.i <- glm(PLI.f ~ SHM,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.i)
lrtest(climate.PLI.i, climate.PLI.null)

```

```{r}
# Cool and Wet Anomalies
climate.PLI.null <- glm(PLI.f ~ 1,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.null)

climate.PLI.1a <- glm(PLI.f ~ cool.wet.anomalies.MCMT,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.1a)
lrtest(climate.PLI.1a, climate.PLI.null)

climate.PLI.1b <- glm(PLI.f ~ cool.wet.anomalies.MWMT,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.1b)
lrtest(climate.PLI.1b, climate.PLI.null)

climate.PLI.1c <- glm(PLI.f ~ cool.wet.anomalies.Tmax_sm,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.1c)
lrtest(climate.PLI.1c, climate.PLI.null)

climate.PLI.1d <- glm(PLI.f ~ cool.wet.anomalies.MAP,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.1d)
lrtest(climate.PLI.1d, climate.PLI.null)

climate.PLI.1e <- glm(PLI.f ~ cool.wet.anomalies.PAS,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.1e)
lrtest(climate.PLI.1e, climate.PLI.null)

climate.PLI.1f <- glm(PLI.f ~ cool.wet.anomalies.PPT_sm,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.1f)
lrtest(climate.PLI.1f, climate.PLI.null)

climate.PLI.1g <- glm(PLI.f ~ cool.wet.anomalies.CMI_sm,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.1g)
lrtest(climate.PLI.1g, climate.PLI.null)

climate.PLI.1h <- glm(PLI.f ~ cool.wet.anomalies.AHM,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.1h)
lrtest(climate.PLI.1h, climate.PLI.null)

climate.PLI.1i <- glm(PLI.f ~ cool.wet.anomalies.SHM,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.1i)
lrtest(climate.PLI.1i, climate.PLI.null)


```
```{r}
climate.PLI.2a <- glm(PLI.f ~ years_since + MWMT,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.2a)
lrtest(climate.PLI.b, climate.PLI.2a)

climate.PLI.2b <- glm(PLI.f ~ years_since  + MWMT + NFFD_sp,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.2b)
lrtest(climate.PLI.2b, climate.PLI.2a)

climate.PLI.2c <- glm(PLI.f ~ years_since  +  NFFD_sp,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.2c)
lrtest(climate.PLI.2b, climate.PLI.2c)

climate.PLI.2d <- glm(PLI.f ~ years_since + NFFD_sp + cool.wet.anomalies.MCMT ,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.2d)
lrtest(climate.PLI.2c, climate.PLI.2d)

climate.PLI.2e <- glm(PLI.f ~ years_since + NFFD_sp + cool.wet.anomalies.MCMT + NFFD_sp*years_since,
                        family = binomial(link="logit"), data=climate)
summary(climate.PLI.2e)
lrtest(climate.PLI.2e, climate.PLI.2d)


```





