---
title: "PLI_site"
author: "Nat"
date: "2024-09-11"
output: html_document
---

```{r}

bin_dis_GIS1 <- bin_dis_GIS1

bin_dis_GIS1$BEC_Subzone <- factor(bin_dis_GIS1$BEC_Subzone, 
                                                 levels = c("dk", "xm", "dc", "mk", "xc"))
bin_dis_GIS1$BEC_Zone <- factor(bin_dis_GIS1$BEC_Zone,
                                                  levels = c("IDF", "SBPS"))
bin_dis_GIS1$PARENT_SOILS <- factor(bin_dis_GIS1$PARENT_SOILS,
                                    levels = c("TILL", "GLACIOLACUSTRINE", "GLACIOFLUVIAL"))
bin_dis_GIS1 %>% 
  group_by(PARENT_SOILS) %>% 
  summarize(n = n())

```


```{r}
pairs(~ Aspect + Beers_aspect + Elevation + Slope + Solar_Radiation +TWI, 
      data=bin_dis_GIS1, main="Scatterplot Matrix for Site data")
```


```{r}
site.PLI.null <- glm(PLI.f ~ 1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.null)

site.PLI.a <- glm(PLI.f ~ years_since ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.a)
lrtest(site.PLI.a, site.PLI.null)

site.PLI.b <- glm(PLI.f ~ Slope  ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.b)
lrtest(site.PLI.b, site.PLI.null)

site.PLI.c <- glm(PLI.f ~ Elevation ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.d)
lrtest(site.PLI.d, site.PLI.null)

site.PLI.d <- glm(PLI.f ~ Solar_Radiation ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.f)
lrtest(site.PLI.f, site.PLI.null)

site.PLI.e <- glm(PLI.f ~ TWI ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.g)
lrtest(site.PLI.g, site.PLI.null)

site.PLI.f <- glm(PLI.f ~ BEC_Zone ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.h)
lrtest(site.PLI.h, site.PLI.null)

site.PLI.g <- glm(PLI.f ~ BEC_Subzone ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.i)
lrtest(site.PLI.i, site.PLI.null)

site.PLI.h <- glm(PLI.f ~ PARENT_SOILS ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.k)
lrtest(site.PLI.k, site.PLI.null)

site.PLI.i <- glm(PLI.f ~ Latitude,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.l)
lrtest(site.PLI.l, site.PLI.null)

site.PLI.j <- glm(PLI.f ~ Longitude,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.m)
lrtest(site.PLI.m, site.PLI.null)

site.PLI.k <- glm(PLI.f ~ Slope + I(Slope*sin(Aspect*(pi/180))) + I(Slope*cos(Aspect*(pi/180))) ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.b)
lrtest(site.PLI.b, site.PLI.null)

```

```{r}
site.PLI.2a <- glm(PLI.f ~ years_since + BEC_Zone,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2a)
lrtest(site.PLI.2a, site.PLI.a)
anova(site.PLI.a, site.PLI.2a)

site.PLI.2b <- glm(PLI.f ~ years_since + BEC_Subzone + PARENT_SOILS + Slope + Slope*sin(Aspect*(pi/180)) + Slope*cos(Aspect*(pi/180)) ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2b)
lrtest(site.PLI.2b, glm(PLI.f ~ years_since + BEC_Subzone,
    family=binomial(link = "logit"), data=bin_dis_GIS1))

site.PLI.2c <- glm(PLI.f ~ years_since + BEC_Zone + PARENT_SOILS,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2c)
lrtest(site.PLI.2c, site.PLI.2a)

site.PLI.2d <- glm(PLI.f ~ years_since + BEC_Zone + PARENT_SOILS + Slope + Slope*sin(Aspect*(pi/180)) + Slope*cos(Aspect*(pi/180)) ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2d)
lrtest(site.PLI.2d, site.PLI.2c)
lrtest(site.PLI.2d, glm(PLI.f ~ years_since + BEC_Subzone,
    family=binomial(link = "logit"), data=bin_dis_GIS1))

site.PLI.2e <- glm(PLI.f ~ years_since + BEC_Zone + PARENT_SOILS + Slope + I(Slope*sin(Aspect*(pi/180))) + I(Slope*cos(Aspect*(pi/180))) + Elevation,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2e)
lrtest(site.PLI.2e, site.PLI.2d)

site.PLI.2f <- glm(PLI.f ~ years_since + BEC_Zone + PARENT_SOILS + Solar_Radiation,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2f)
lrtest(site.PLI.2f, site.PLI.2c)

site.PLI.2g <- glm(PLI.f ~ years_since + BEC_Zone + PARENT_SOILS + Elevation+ Solar_Radiation,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2g)
lrtest(site.PLI.2g, site.PLI.2f)

site.PLI.2h <- glm(PLI.f ~ years_since + BEC_Zone + PARENT_SOILS  + TWI +Elevation,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2h)
lrtest(site.PLI.2h, site.PLI.2i)

site.PLI.2i <- glm(PLI.f ~ years_since + BEC_Zone + PARENT_SOILS   + TWI ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2i)
lrtest(site.PLI.2i, site.PLI.2c)

site.PLI.2j <- glm(PLI.f ~ years_since + BEC_Zone + PARENT_SOILS  + Slope ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2j)
lrtest(site.PLI.2i, site.PLI.2j)

range(bin_dis_GIS1$Slope)
```


```{r}
site.PLI.2a <- glm(PLI.f ~ years_since + BEC_Subzone,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2a)
lrtest(site.PLI.2a, site.PLI.a)
anova(site.PLI.a, site.PLI.2a)

site.PLI.2b <- glm(PLI.f ~ years_since + BEC_Subzone + PARENT_SOILS + Slope + Slope*sin(Aspect*(pi/180)) + Slope*cos(Aspect*(pi/180)) ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2b)
lrtest(site.PLI.2b, glm(PLI.f ~ years_since + BEC_Subzone,
    family=binomial(link = "logit"), data=bin_dis_GIS1))

site.PLI.2c <- glm(PLI.f ~ years_since + BEC_Subzone + PARENT_SOILS,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2c)
lrtest(site.PLI.2c, site.PLI.2a)

site.PLI.2d <- glm(PLI.f ~ years_since + BEC_Subzone + PARENT_SOILS + Slope + I(Slope*sin(Aspect*(pi/180)) + Slope*cos(Aspect*(pi/180))) ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2d)
lrtest(site.PLI.2d, site.PLI.2c)
lrtest(site.PLI.2d, glm(PLI.f ~ years_since + BEC_Subzone + PARENT_SOILS + Slope,
    family=binomial(link = "logit"), data=bin_dis_GIS1))

site.PLI.2e <- glm(PLI.f ~ years_since + BEC_Zone + PARENT_SOILS + Slope + I(Slope*sin(Aspect*(pi/180))) + I(Slope*cos(Aspect*(pi/180))) + Elevation,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2e)
lrtest(site.PLI.2e, site.PLI.2d)

site.PLI.2f <- glm(PLI.f ~ years_since + BEC_Subzone + PARENT_SOILS + Solar_Radiation,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2f)
lrtest(site.PLI.2f, site.PLI.2c)

site.PLI.2g <- glm(PLI.f ~ years_since + BEC_Zone + PARENT_SOILS + Elevation+ Solar_Radiation,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2g)
lrtest(site.PLI.2g, site.PLI.2f)

site.PLI.2h <- glm(PLI.f ~ years_since + BEC_Zone + PARENT_SOILS  + TWI +Elevation,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2h)
lrtest(site.PLI.2h, site.PLI.2i)

site.PLI.2i <- glm(PLI.f ~ years_since + BEC_Subzone + PARENT_SOILS   + TWI ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2i)
lrtest(site.PLI.2i, site.PLI.2c)

site.PLI.2j <- glm(PLI.f ~ years_since + BEC_Subzone + PARENT_SOILS  + Slope ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2j)
lrtest(site.PLI.2i, site.PLI.2j)

mean(bin_dis_GIS1$Slope)

table(bin_dis_GIS1$FIRE_NUMBER_1)
```

# okay so maybe now I look at interactions for slope/aspect/etc.?
```{r}
site.PLI.2j <- glm(PLI.f ~ years_since + BEC_Subzone + Slope+ PARENT_SOILS  ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2j)
lrtest(site.PLI.2i, site.PLI.2j)

site.PLI.2k <- glm(PLI.f ~ years_since + BEC_Subzone  ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2k)
lrtest(site.PLI.2k, site.PLI.2j)
```

```{r}
site.PLI.4a <- glm(PLI.f ~ years_since + BEC_Zone + Latitude,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.4a)
lrtest(site.PLI.4a, site.PLI.a)
anova(site.PLI.a, site.PLI.4a)

site.PLI.4b <- glm(PLI.f ~ years_since + BEC_Subzone + Latitude,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.4b)
lrtest(site.PLI.4b, site.PLI.a)
anova(site.PLI.4a, site.PLI.4b)

site.PLI.4c <- glm(PLI.f ~ years_since +  BEC_Subzone,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.4c)
lrtest(site.PLI.4b, site.PLI.4c)

bin_dis_GIS1$yhat.PLI.Zone <- fitted(site.PLI.4a)
bin_dis_GIS1$yhat.PLI.Subzone <- fitted(site.PLI.4c)
pROC::auc(bin_dis_GIS1$PLI.f, bin_dis_GIS1$yhat.PLI.Zone)
pROC::auc(bin_dis_GIS1$PLI.f, bin_dis_GIS1$yhat.PLI.Subzone)

```


