---
title: "Models2"
author: "Nat"
date: "2024-08-07"
output: html_document
---



structural

```{r}
pairs(~ Distance  +CROWN_CLOSURE_1 +PROJ_AGE_1_1 +PROJ_HEIGHT_1_1 +DISTANCE_TO_PERIMETER +
        PATCH_SIZE_1 + MEAN, 
      data=bin_dis_GIS1, main="Scatterplot Matrix for Structure data")

pairs(~ PATCH_SIZE_1 + MEAN + BARC.x, 
      data=bin_dis_GIS1, main="Scatterplot Matrix for Structure data")
```


Step 1
```{r}

logistic.null <- glm(PLI.f ~ 1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.null)

structure.PLIa <- glm(PLI.f ~ Distance ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIa) #not significant on own

structure.PLIb <- glm(PLI.f ~ years_since ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIb) #significant on own

structure.PLIc <- glm(PLI.f ~ CROWN_CLOSURE_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIc) #not significant on own

structure.PLId <- glm(PLI.f ~ PROJ_AGE_1_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLId) #significant on own

structure.PLIe <- glm(PLI.f ~ PROJ_HEIGHT_1_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIe) #significant on own

structure.PLIf <- glm(PLI.f ~ DISTURBANCE_TYPE_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIf) #significant on own 

structure.PLIg <- glm(PLI.f ~ DISTANCE_TO_PERIMETER ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIg) #significant on own

structure.PLIh <- glm(PLI.f ~ BURN_SEVERITY_RATING_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIh) #significant on own

structure.PLIi <- glm(PLI.f ~ MEAN ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIi)

structure.PLIj <- glm(PLI.f ~ PLI_percent ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIj)

structure.PLIk <- glm(PLI.f ~ PATCH_SIZE_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIk)

structure.PLIl <- glm(PLI.f ~ BARC.x ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIl)
lrtest(structure.PLIl, logistic.null)

lrtest(structure.PLIj, logistic.null)

```
Compare categorical variables to null model
```{r}
library(lmtest)
lrtest(structure.PLIf, logistic.null)
lrtest(structure.PLIh, logistic.null)
```

Step 2 with dNBR
```{r}
structure.PLI.2a <- glm(PLI.f ~ years_since  + MEAN  +PLI_percent,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2a)
lrtest(structure.PLI.2a, glm(PLI.f ~ years_since  + MEAN,family=binomial(link = "logit"), data=bin_dis_GIS1))

structure.PLI.2b <- glm(PLI.f ~ years_since  + MEAN  + PLI_percent + PROJ_HEIGHT_1_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2b)
lrtest(structure.PLI.2b, structure.PLI.2a) 

structure.PLI.2c <- glm(PLI.f ~ years_since  + MEAN  + PLI_percent+ DISTANCE_TO_PERIMETER,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2c)
lrtest(structure.PLI.2c, structure.PLI.2a) 

structure.PLI.2d <- glm(PLI.f ~ years_since  + MEAN  + PLI_percent+ PATCH_SIZE_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2d)
lrtest(structure.PLI.2d, structure.PLI.2a) #restrictions justified, remove PROJ_HEIGHT_1_1

structure.PLI.2e <- glm(PLI.f ~ years_since  + MEAN  + PLI_percent + PROJ_AGE_1_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2e)
lrtest(structure.PLI.2e, structure.PLI.2a)

structure.PLI.2f <- glm(PLI.f ~ years_since  + MEAN  + PLI_percent + Distance,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2f)
lrtest(structure.PLI.2f, structure.PLI.2a) # restrictions justified, remove SPECIES_CD_2_1

structure.PLI.2g <- glm(PLI.f ~ years_since  + MEAN  + PLI_percent + DISTURBANCE_TYPE_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2g)
lrtest(structure.PLI.2g, structure.PLI.2a) #restrictions justified, remove PROJ_HEIGHT_1_1

structure.PLI.2h <- glm(PLI.f ~ years_since  + MEAN  + PLI_percent + CROWN_CLOSURE_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2h)
lrtest(structure.PLI.2h, structure.PLI.2a) #restrictions justified, remove DISTANCE_TO_PERIMETER

```

```{r}
structure.PLI.3a <- glm(PLI.f ~ years_since  + BARC.x  +PLI_percent,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3a)
lrtest(structure.PLI.3a, glm(PLI.f ~ years_since  + BARC.x,family=binomial(link = "logit"), data=bin_dis_GIS1))

structure.PLI.3b <- glm(PLI.f ~ years_since  + BARC.x  + PLI_percent + PROJ_HEIGHT_1_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3b)
lrtest(structure.PLI.3b, structure.PLI.3a) 

structure.PLI.3c <- glm(PLI.f ~ years_since  + BARC.x  + PLI_percent+ DISTANCE_TO_PERIMETER,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3c)
lrtest(structure.PLI.3c, structure.PLI.3a) 

structure.PLI.3d <- glm(PLI.f ~ years_since  + BARC.x  + PLI_percent+ PATCH_SIZE_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3d)
lrtest(structure.PLI.3d, structure.PLI.3a) #restrictions justified, remove PROJ_HEIGHT_1_1

structure.PLI.3e <- glm(PLI.f ~ years_since  + BARC.x  + PLI_percent + PROJ_AGE_1_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3e)
lrtest(structure.PLI.3e, structure.PLI.3a)

structure.PLI.3f <- glm(PLI.f ~ years_since  + BARC.x  + PLI_percent + Distance,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3f)
lrtest(structure.PLI.3f, structure.PLI.3a) # restrictions justified, remove SPECIES_CD_2_1

structure.PLI.3g <- glm(PLI.f ~ years_since  + BARC.x  + PLI_percent + DISTURBANCE_TYPE_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3g)
lrtest(structure.PLI.3g, structure.PLI.3a) #restrictions justified, remove PROJ_HEIGHT_1_1

structure.PLI.3h <- glm(PLI.f ~ years_since  + BARC.x  + PLI_percent + CROWN_CLOSURE_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3h)
lrtest(structure.PLI.3h, structure.PLI.3a) #restrictions justified, remove DISTANCE_TO_PERIMETER

```
# BARC or dNBR?

```{r}
structure.PLI.3a <- glm(PLI.f ~ years_since  + BARC.x  +PLI_percent,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3a)

structure.PLI.2a <- glm(PLI.f ~ years_since  + MEAN  +PLI_percent,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2a)

```



```{r}
bin_dis_GIS1$linpred.GLM2a <- predict(structure.PLI.2b) # Estimated logit using the linear part
bin_dis_GIS1$yhat.GLM2a <- fitted(structure.PLI.2b) # Estimated probability using inverse logityhat values
bin_dis_GIS1$resid.GLM2a <- resid(structure.PLI.2b) # the deviances 

# Graph of predicted probabilities ranges for dead versus alive
# Would like the dead=0 (it is alive) trees to have all low predicted prob(dead) 
# and the dead=1 (it is dead) trees to all have high predicted prob (dead). 
par(mfrow=c(1,1),mai=c(1,1,0.6,0.6),cex=0.8)
plot(bin_dis_GIS1$PLI.f,bin_dis_GIS1$yhat.GLM2a,pch=8,
  main="Model 1: Predicted Prob for Seedling Occurrence (PLI)",
  ylab="Predicted Prob(occurrence)", xlab="Seedling (=1) or No seedling(=0) as Recorded")
par(mfrow=c(1,1),mai=c(1,1,1,1),cex=1)
```

```{r}
# GLM1
cutoff <- 0.5 # you can play around with different cutoff values
n <- dim(bin_dis_GIS1)[1]
#bin_dis_GIS1$PLI_count_bin <- as.numeric(levels(bin_dis_GIS1$PLI_count_bin))[bin_dis_GIS1$PLI_count_bin]
obs <- bin_dis_GIS1$PLI_count_bin
pred <- ifelse(bin_dis_GIS1$yhat.GLM2a >= cutoff, 1,0)

bin_dis_GIS1$GLM2a <- ifelse( obs == 1 & (obs - pred) == 0, 1, 0) ; a <- sum(bin_dis_GIS1$GLM2a) # a: true positives
bin_dis_GIS1$GLM2c <- ifelse( obs == 1 & (obs - pred) == 1, 1, 0) ; c <- sum(bin_dis_GIS1$GLM2c) # c: false negative
bin_dis_GIS1$GLM2b <- ifelse( obs == 0 & (obs - pred) == -1, 1, 0) ; b <- sum(bin_dis_GIS1$GLM2b) # b: false positives
bin_dis_GIS1$GLM2d <- ifelse( obs == 0 & (obs - pred) == 0, 1, 0) ; d <- sum(bin_dis_GIS1$GLM2d) # d: true negatives

# general confusion matrix layout
matrix(c("a","c" , "b","d"), nrow=2, ncol=2)
CM.GLM2 <- matrix(c(a,c , b,d), nrow=2, ncol=2)
CM.GLM2



# overall accuracy = (a+d)/n
GLM2.oa <- (a+d)/n
GLM2.sensitivity <- a/(a+c)
GLM2.specificity <- d/(b+d)
kappa.bit <- (a+b)*(a+c)+(c+d)*(d+b)
GLM2.kappa <- (  ((a+d)/n)  - (kappa.bit/n^2) ) / (1- (kappa.bit/n^2) )
GLM2.TSS <- GLM2.sensitivity + GLM2.specificity -1

GLM2.predacc <- c(GLM2.oa, GLM2.sensitivity, GLM2.specificity, GLM2.kappa,GLM2.TSS)

GLM2.auc <-pROC::auc(bin_dis_GIS1$PLI_count_bin,bin_dis_GIS1$yhat.GLM2a)
plot(pROC::roc(bin_dis_GIS1$PLI_count_bin,bin_dis_GIS1$yhat.GLM2a),auc.polygon=T)
```

```