---
title: "Creating dataframes"
author: '3034081184'
date: "2024-03-22"
output: html_document
---


Load packages and data
```{r}
library(tidyverse)
library(lmtest)

regen <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/Regen_2023_ALL.csv"
regen <- read.csv(regen)
GIS_i <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/Regen_Points_May2.csv"
GIS_i <- read.csv(GIS_i)
clipGis <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/PossiblePlot.csv"
clipGis <- read.csv(clipGis)
distance <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/distance.csv"
distance <- read.csv(distance)
fire_severity <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Dataframes/FireSeverity.csv"
fire_severity <- read.csv(fire_severity)

```

# Format plot data
```{r}
# Fill in blank species, NR = no regen
regen$Species <- sub("^$", "NR", regen$Species)
regen$Species <- sub("ACT", "AT", regen$Species)
regen$Species <- sub("SW", "SX", regen$Species)
regen$Species <- sub("SE", "SX", regen$Species)
regen$Species <- sub("SX", "SX", regen$Species)

regen <- regen %>%
  mutate(
    x0 = ifelse(is.na(x0), 0, x0),
    x10 = ifelse(is.na(x10), 0, x10),
    x30 = ifelse(is.na(x30), 0, x30),
    x130 = ifelse(is.na(x130), 0, x130)
  )

regen <- regen %>%
  mutate(Species = ifelse(
    (x0 > 0 | x10 > 0 | x30 > 0 | x130 > 0) & Species == "NR",
    "PLI",
    Species
  ))




# get rid of unnecessary columns
regen<- regen %>% 
  select(Card,Quandrant,Species,Notes,x0,x10,x30,x130) 

# new column for species by plot
regen$Plot_Sp <- paste(regen$Card, regen$Species, sep = "")

#new column for total of seedlings per wedge by species
regen<- regen%>% 
  mutate(total = rowSums(cbind(regen$x0,regen$x10,regen$x30,regen$x130),na.rm=TRUE))

#combine different wedges by height class

regen_only_total <- regen %>% 
  group_by(Card, Species, Plot_Sp) %>% 
  summarise(across(total, sum))

regen_only_x0 <- regen %>% 
  group_by(Plot_Sp) %>% 
  summarise(x0 = sum(x0, na.rm = TRUE))

regen_only_x10 <- regen %>% 
  group_by(Plot_Sp) %>% 
  summarise(x10 = sum(x10, na.rm = TRUE))

regen_only_x30 <- regen %>% 
  group_by(Plot_Sp) %>% 
  summarise(x30 = sum(x30, na.rm = TRUE))

regen_only_x130 <- regen %>% 
  group_by(Plot_Sp) %>% 
  summarise(x130 = sum(x130, na.rm = TRUE))

#combine into 1 data frame

regen_all <- full_join(regen_only_total, regen_only_x0, by = "Plot_Sp") %>% 
  full_join(regen_only_x10, by = "Plot_Sp") %>% 
  full_join(regen_only_x30, by = "Plot_Sp") %>%
  full_join(regen_only_x130, by = "Plot_Sp")

# now i want to have columns for each species

create_species_columns <- function(data, species_list, columns) {
  for (species in species_list) {
    for (col in columns) {
      new_col_name <- paste0(species, "_", col)
      data[[new_col_name]] <- ifelse(data$Species == species, data[[col]], 0)
    }
  }
  return(data)
}
species_list <- c("FDI", "PLI", "AT", "SX")
columns <- c("total", "x0", "x10", "x30", "x130")

regen_all <- create_species_columns(regen_all, species_list, columns)



# remove NR rows for plots that have other species present
regen_all <- regen_all %>% 
  group_by(Card) %>% 
  mutate(has_nr = any(Species == "NR"), num_rows = n()) %>% 
  filter(num_rows == 1 | !(has_nr & Species == "NR")) %>% 
  select(-has_nr, -num_rows)


# combine rows for same plot
regen_combo <- regen_all %>%
  group_by(Card) %>%
  summarize(SpeciesAll = paste(Species, collapse = ", "),
            total_count = sum(total),
            total_tph = total_count*200,
            total_x0 = sum(x0),
            total_x10 = sum(x10),
            total_x30 = sum(x30),
            total_x130 = sum(x130),
            FDI_count = sum(FDI_total),
            FDI_tph = FDI_count*200,
            FDI_x0 = sum(FDI_x0),
            FDI_x10 = sum(FDI_x10),
            FDI_x30 = sum(FDI_x30),
            FDI_x130 = sum(FDI_x130),
            PLI_count = sum(PLI_total),
            PLI_tph = PLI_count*200,
            PLI_x0 = sum(PLI_x0),
            PLI_x10 = sum(PLI_x10),
            PLI_x30 = sum(PLI_x30),
            PLI_x130 = sum(PLI_x130),
            AT_count = sum(AT_total),
            AT_x0 = sum(AT_x0),
            AT_x10 = sum(AT_x10),
            AT_x30 = sum(AT_x30),
            AT_x130 = sum(AT_x130),
            SX_count = sum(SX_total),
            SX_x0 = sum(SX_x0),
            SX_x10 = sum(SX_x10),
            SX_x30 = sum(SX_x30),
            SX_x130 = sum(SX_x130)) %>% 
  ungroup()

# export dataframe
write.csv(regen_combo, "C:/Users/nmac2000/Documents/regen project/Regen/Dataframes/MeasuredPlots.csv")
```

# Add GIS Data
```{r}
# add GIS data
regen$Card <- as.integer(regen$Card)
regen_copy <- regen #don't
regen_copy <- regen_copy %>% 
  rename(SampleSite_ID = Card)
clipped_plots <- semi_join(clipGis, regen_copy, "SampleSite_ID")
forgotten_plots <- anti_join(regen_copy, clipped_plots, "SampleSite_ID")

clipGIS1 <- clipGis %>% 
  select(SampleSite_ID)
forgotten_plots <- forgotten_plots %>% 
  select(SampleSite_ID)
clipGis <- bind_rows(clipGIS1,forgotten_plots)

GIS_i <- GIS_i %>% 
  rename(SampleSite_ID = "Plot_ID")
GIS_i <- semi_join(GIS_i, clipGis, "SampleSite_ID")
GIS_i$Card <- as.integer(GIS_i$SampleSite_ID)
regen_combo$Card <- as.integer(regen_combo$Card, na.rm=TRUE)

#Edit overstory species to our catergories
GIS_i$SPECIES_CD_1_1 <- sub("\\bSX\\b", "SX", GIS_i$SPECIES_CD_1_1)
GIS_i$SPECIES_CD_1_1 <- sub("\\bS\\b", "SX", GIS_i$SPECIES_CD_1_1)
GIS_i$SPECIES_CD_1_1 <- sub("\\bSE\\b", "SX", GIS_i$SPECIES_CD_1_1)
GIS_i$SPECIES_CD_1_1 <- sub("\\bPL\\b", "PLI", GIS_i$SPECIES_CD_1_1)
GIS_i$SPECIES_CD_1_1 <- sub("\\bFD\\b", "FDI", GIS_i$SPECIES_CD_1_1)
GIS_i$SPECIES_CD_1_1 <- sub("\\bPA\\b", "PLI", GIS_i$SPECIES_CD_1_1)

GIS_i$SPECIES_CD_2_1 <- sub("\\bSX\\b", "SX", GIS_i$SPECIES_CD_2_1)
GIS_i$SPECIES_CD_2_1 <- sub("\\bS\\b", "SX", GIS_i$SPECIES_CD_2_1)
GIS_i$SPECIES_CD_2_1 <- sub("\\bSE\\b", "SX", GIS_i$SPECIES_CD_2_1)
GIS_i$SPECIES_CD_2_1 <- sub("\\bPL\\b", "PLI", GIS_i$SPECIES_CD_2_1)
GIS_i$SPECIES_CD_2_1 <- sub("\\bFD\\b", "FDI", GIS_i$SPECIES_CD_2_1)
GIS_i$SPECIES_CD_2_1 <- sub("\\bPA\\b", "PLI", GIS_i$SPECIES_CD_2_1)

GIS_i$SPECIES_CD_3_1 <- sub("\\bSX\\b", "SX", GIS_i$SPECIES_CD_3_1)
GIS_i$SPECIES_CD_3_1 <- sub("\\bS\\b", "SX", GIS_i$SPECIES_CD_3_1)
GIS_i$SPECIES_CD_3_1 <- sub("\\bSE\\b", "SX", GIS_i$SPECIES_CD_3_1)
GIS_i$SPECIES_CD_3_1 <- sub("\\bPL\\b", "PLI", GIS_i$SPECIES_CD_3_1)
GIS_i$SPECIES_CD_3_1 <- sub("\\bFD\\b", "FDI", GIS_i$SPECIES_CD_3_1)
GIS_i$SPECIES_CD_3_1 <- sub("\\bPA\\b", "PLI", GIS_i$SPECIES_CD_3_1)

GIS_i$SPECIES_CD_4_1 <- sub("\\bSX\\b", "SX", GIS_i$SPECIES_CD_4_1)
GIS_i$SPECIES_CD_4_1 <- sub("\\bS\\b", "SX", GIS_i$SPECIES_CD_4_1)
GIS_i$SPECIES_CD_4_1 <- sub("\\bSE\\b", "SX", GIS_i$SPECIES_CD_4_1)
GIS_i$SPECIES_CD_4_1 <- sub("\\bPL\\b", "PLI", GIS_i$SPECIES_CD_4_1)
GIS_i$SPECIES_CD_4_1 <- sub("\\bFD\\b", "FDI", GIS_i$SPECIES_CD_4_1)
GIS_i$SPECIES_CD_4_1 <- sub("\\bPA\\b", "PLI", GIS_i$SPECIES_CD_4_1)

GIS_i$SPECIES_CD_5_1 <- sub("\\bSX\\b", "SX", GIS_i$SPECIES_CD_5_1)
GIS_i$SPECIES_CD_5_1 <- sub("\\bS\\b", "SX", GIS_i$SPECIES_CD_5_1)
GIS_i$SPECIES_CD_5_1 <- sub("\\bSE\\b", "SX", GIS_i$SPECIES_CD_5_1)
GIS_i$SPECIES_CD_5_1 <- sub("\\bPL\\b", "PLI", GIS_i$SPECIES_CD_5_1)
GIS_i$SPECIES_CD_5_1 <- sub("\\bFD\\b", "FDI", GIS_i$SPECIES_CD_5_1)
GIS_i$SPECIES_CD_5_1 <- sub("\\bPA\\b", "PLI", GIS_i$SPECIES_CD_5_1)

GIS_i$SPECIES_CD_6_1 <- sub("\\bSX\\b", "SX", GIS_i$SPECIES_CD_6_1)
GIS_i$SPECIES_CD_6_1 <- sub("\\bS\\b", "SX", GIS_i$SPECIES_CD_6_1)
GIS_i$SPECIES_CD_6_1 <- sub("\\bSE\\b", "SX", GIS_i$SPECIES_CD_6_1)
GIS_i$SPECIES_CD_6_1 <- sub("\\bPL\\b", "PLI", GIS_i$SPECIES_CD_6_1)
GIS_i$SPECIES_CD_6_1 <- sub("\\bFD\\b", "FDI", GIS_i$SPECIES_CD_6_1)
GIS_i$SPECIES_CD_6_1 <- sub("\\bPA\\b", "PLI", GIS_i$SPECIES_CD_6_1)


#Aspect

#northeast-to-southwest facing scale (Beers et al., 1996)
#Taspect = sin(aspect + 45) + 1



GIS_i$Beers_aspect <- sin(GIS_i$Aspect*(pi/180) + 45) + 1


#Convert Aspect
assign_direction <- function(angle) {
  ifelse(is.na(angle), NA,  # Handle NA values
         ifelse(angle >= 315 || angle < 45, "N",
                ifelse(angle >= 45 && angle < 135, "E",
                       ifelse(angle >= 135 && angle < 225, "S", "W"))))
  }


# Apply the function to the data column
GIS_i$Azimuth <- sapply(GIS_i$Aspect, assign_direction)

write.csv(GIS_i, "C:/Users/nmac2000/Documents/regen project/Regen/Dataframes/GIS_fixed.csv")

```

# Fire Severity
```{r}
regen_combo$SampleSite_ID <- as.integer(regen_combo$Card, na.rm=TRUE)
regen_GIS <- left_join(regen_combo,GIS_i, by = "SampleSite_ID") %>% 
  ungroup()


fire_severity <- fire_severity %>% 
  select(Card, MEAN) %>% 
  rename(SampleSite_ID = Card)

# Fix some fire severity values that were close to other plots
new_rows <- data.frame(
  SampleSite_ID = c(1153, 1182, 1500, 1501, 1502, 1503, 1531, 1192, 1484, 1504),
  MEAN = c(
    fire_severity$MEAN[which(fire_severity$SampleSite_ID == 2626)],
    fire_severity$MEAN[which(fire_severity$SampleSite_ID == 2644)],
    fire_severity$MEAN[which(fire_severity$SampleSite_ID == 1760)],
    fire_severity$MEAN[which(fire_severity$SampleSite_ID == 1761)],
    fire_severity$MEAN[which(fire_severity$SampleSite_ID == 1770)],
    fire_severity$MEAN[which(fire_severity$SampleSite_ID == 1771)],
    fire_severity$MEAN[which(fire_severity$SampleSite_ID == 1791)],
    fire_severity$MEAN[which(fire_severity$SampleSite_ID == 2644)],
    mean(c(0.485442, 0.462872, 0.575654, 0.470040)),
    mean(c(0.356386, 0.246404))
  )
)

# Combine the new rows with the existing dataframe
fire_severity <- bind_rows(fire_severity, new_rows)


fire_severity <- within(fire_severity, {   
  BARC.x <- NA # need to initialize variable
  BARC.x[MEAN < .105] <- 1
  BARC.x[MEAN >= .105 & MEAN < 0.275] <- 2
  BARC.x[MEAN >= 0.275 & MEAN < 0.66] <- 3
  BARC.x[MEAN >= 0.66] <- 4
   } )

regen_GIS <- full_join(regen_GIS, fire_severity, by = "SampleSite_ID")


regen_GIS %>% filter(is.na(MEAN))
```

# Adding distance to live tree
```{r}

distance <-  distance %>% 
  select(SampleSite_ID, Distance)
regen_GIS <- full_join(regen_GIS, distance, by = "SampleSite_ID")


regen_GIS <- regen_GIS %>%
  mutate(Distance = ifelse(SampleSite_ID == 1511, 4, Distance)) %>%
  mutate(Distance = ifelse(SampleSite_ID == 3, 4, Distance)) %>% 
  mutate(Distance = ifelse(SampleSite_ID == 330, 4, Distance))
```

# Removing Unmeasured Plots
```{r}
not_measured_list <-c(2042, 1840, 1701, 2208, 1609, 2646, 1598, 1942, 2043, 1623, 2269, 2115, 1482, 2213, 2334,
                               1936, 1724, 193, 318, 1209, 1267, 499, 1836, 361, 545, 907,
                               1467, 1297, 1423, 1831, 585, 1796, 2271, 1807, 865, 315, 329)

not_measured <- regen_GIS %>% 
  filter(SampleSite_ID %in% not_measured_list) %>% 
  select(SampleSite_ID)

regen_GIS <- regen_GIS %>%
  distinct(SampleSite_ID, .keep_all = T) %>% 
  filter(!SampleSite_ID %in% not_measured$SampleSite_ID) %>% 
  filter(!SampleSite_ID %in% c(456, 496, 1108, 1422, 1514, 1643)) %>% 
  filter(!is.na(UNIQUE_ID))

regen_GIS %>% 
  filter(is.na(Distance))
write.csv(regen_GIS,  "C:/Users/nmac2000/Documents/regen project/Regen/Dataframes/regen_GIS.csv")
regen_GIS <- read.csv("C:/Users/nmac2000/Documents/regen project/Regen/Dataframes/regen_GIS.csv")
```



# Occurrence
```{r}
regen_binary <- regen_GIS %>% 
  mutate(total_count_bin = ifelse(total_count>0,1,0),
         total_x0_bin = ifelse(total_x0>0,1,0),
         total_x10_bin = ifelse(total_x10>0,1,0),
         total_x30_bin = ifelse(total_x30>0,1,0),
         total_x130_bin = ifelse(total_x130>0,1,0),
         FDI_count_bin = ifelse(FDI_count>0,1,0),
         FDI_x0_bin = ifelse(FDI_x0>0,1,0),
         FDI_x10_bin = ifelse(FDI_x10>0,1,0),
         FDI_x30_bin = ifelse(FDI_x30>0,1,0),
         FDI_x130_bin = ifelse(FDI_x130>0,1,0),
         PLI_count_bin = ifelse(PLI_count>0,1,0),
         PLI_x0_bin = ifelse(PLI_x0>0,1,0),
         PLI_x10_bin = ifelse(PLI_x10>0,1,0),
         PLI_x30_bin = ifelse(PLI_x30>0,1,0),
         PLI_x130_bin = ifelse(PLI_x130>0,1,0),
         AT_count_bin = ifelse(AT_count>0,1,0),
         AT_x0_bin = ifelse(AT_x0>0,1,0),
         AT_x10_bin = ifelse(AT_x10>0,1,0),
         AT_x30_bin = ifelse(AT_x30>0,1,0),
         AT_x130_bin = ifelse(AT_x130>0,1,0),
         SX_count_bin = ifelse(SX_count>0,1,0),
         SX_x0_bin = ifelse(SX_x0>0,1,0),
         SX_x10_bin = ifelse(SX_x10>0,1,0),
         SX_x30_bin = ifelse(SX_x30>0,1,0),
         SX_x130_bin = ifelse(SX_x130>0,1,0))


write.csv(regen_binary, "C:/Users/nmac2000/Documents/regen project/Regen/Dataframes/regen_binary.csv")
# ? not what why this is: write.csv(bin_GIS, "C:/Users/nmac2000/Documents/regen project/Regen/Dataframes/binary_GIS.csv")


```

# For Analysis
```{r}
bin_dis_GIS1 <- read.csv("C:/Users/nmac2000/Documents/regen project/Regen/Dataframes/regen_binary.csv")

# ensure y variable is a factor for seedling presence vs absence
bin_dis_GIS1$PLI.f <- as.factor(bin_dis_GIS1$PLI_count_bin)
bin_dis_GIS1$FDI.f <- as.factor(bin_dis_GIS1$FDI_count_bin)
# y=1 for regeneration, y=0 for no regeneration
class(bin_dis_GIS1$PLI.f)
bin_dis_GIS1$Distance <- as.numeric(bin_dis_GIS1$Distance)
bin_dis_GIS1$CROWN_CLOSURE_1 <- as.numeric(bin_dis_GIS1$CROWN_CLOSURE_1)
bin_dis_GIS1$PROJ_AGE_1_1 <- as.numeric(bin_dis_GIS1$PROJ_AGE_1_1)
bin_dis_GIS1$PROJ_HEIGHT_1_1 <- as.numeric(bin_dis_GIS1$PROJ_HEIGHT_1_1)
bin_dis_GIS1$DISTANCE_TO_PERIMETER <- as.numeric(bin_dis_GIS1$DISTANCE_TO_PERIMETER)
bin_dis_GIS1$years_since <- as.numeric(2023-bin_dis_GIS1$FIRE_YEAR_1)
bin_dis_GIS1$DISTURBANCE_TYPE_1 <- as.factor(bin_dis_GIS1$DISTURBANCE_TYPE_1)
bin_dis_GIS1$SPECIES_CD_1_1 <- factor(bin_dis_GIS1$SPECIES_CD_1_1, levels = c("PLI", "FDI", "AT", "SX"))
bin_dis_GIS1$BARC.x <- as.factor(bin_dis_GIS1$BARC.x)

# remove plots with NA values
# remove VRI non-treed sites
bin_dis_GIS1 <- bin_dis_GIS1 %>% 
  filter(SPECIES_CD_1_1 != "")

# remove MS BEC zone (not enough observations)
bin_dis_GIS1 <- bin_dis_GIS1 %>% 
  filter(BEC_Zone != "MS")

# remove organic and rock parent material
bin_dis_GIS1 <- bin_dis_GIS1 %>% 
  filter(!PARENT_SOILS %in% c("ORGANIC ", "ROCK "))

# combine parent material categories
table(bin_dis_GIS1$PARENT_SOILS)
table(bin_dis_GIS$PARENT_SOILS)
bin_dis_GIS1 <- bin_dis_GIS1 %>%
  mutate(PARENT_SOILS = ifelse(PARENT_SOILS == "FLUVIAL ", "GLACIOFLUVIAL ", PARENT_SOILS)) %>% 
  mutate(PARENT_SOILS = ifelse(PARENT_SOILS == "LACUSTRINE ", "GLACIOLACUSTRINE ", PARENT_SOILS)) %>% 
  mutate(PARENT_SOILS = trimws(PARENT_SOILS))

write.csv(bin_dis_GIS1, "C:/Users/nmac2000/Documents/regen project/Regen/Dataframes/bin_dis_GIS1.csv")
```


