---
title: "Models"
author: '3034081184'
date: "2024-05-23"
output: html_document
---

```{r}
#need to figure out data frames for everything and clean up code
bin_dis_GIS1 <- bin_dis_GIS %>%
  distinct(SampleSite_ID, .keep_all = T)

```

structural
```{r}
names(bin_dis_GIS1)  # print out the column (i.e., variable) names
dim(bin_dis_GIS1)    # number of rows and columns
head(bin_dis_GIS1)  # print out the first few lines of data

# ensure y variable is a factor for dead versus alive
bin_dis_GIS1$PLI.f <- as.factor(bin_dis_GIS1$PLI_count_bin)
bin_dis_GIS1$FDI.f <- as.factor(bin_dis_GIS1$FDI_count_bin)
# y=1 for dead trees, y=0 for live trees
class(bin_dis_GIS1$PLI.f)
bin_dis_GIS1$Distance <- as.numeric(bin_dis_GIS1$Distance)
bin_dis_GIS1$CROWN_CLOSURE_1 <- as.numeric(bin_dis_GIS1$CROWN_CLOSURE_1)
bin_dis_GIS1$PROJ_AGE_1_1 <- as.numeric(bin_dis_GIS1$PROJ_AGE_1_1)
bin_dis_GIS1$PROJ_HEIGHT_1_1 <- as.numeric(bin_dis_GIS1$PROJ_HEIGHT_1_1)
bin_dis_GIS1$DISTANCE_TO_PERIMETER <- as.numeric(bin_dis_GIS1$DISTANCE_TO_PERIMETER)
bin_dis_GIS1$years_since <- as.factor(bin_dis_GIS1$years_since)
bin_dis_GIS1$DISTURBANCE_TYPE_1 <- as.factor(bin_dis_GIS1$DISTURBANCE_TYPE_1)
bin_dis_GIS1$BURN_SEVERITY_RATING_1 <- as.factor(bin_dis_GIS1$BURN_SEVERITY_RATING_1)

bin_dis_GIS1 <- bin_dis_GIS1 %>% 
  filter(!is.na(Distance), !is.na(years_since), !is.na(CROWN_CLOSURE_1),
         !is.na(PROJ_AGE_1_1), !is.na(PROJ_HEIGHT_1_1), !is.na(DISTURBANCE_TYPE_1),
         !is.na(DISTANCE_TO_PERIMETER), !is.na(BURN_SEVERITY_RATING_1),
         !is.na(PLI.f), !is.na(FDI.f))
```

#why is IBM two different catergories
```{r}
logistic.GLM1a <- glm(PLI.f ~ Distance + years_since + CROWN_CLOSURE_1 + PROJ_AGE_1_1 + 
                        PROJ_HEIGHT_1_1 + DISTURBANCE_TYPE_1 + DISTANCE_TO_PERIMETER + 
                        BURN_SEVERITY_RATING_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM1a)

logistic.GLM1a1 <- glm(PLI.f ~  years_since + 
                        PROJ_HEIGHT_1_1 + DISTURBANCE_TYPE_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM1a1)

logistic.GLM1b <- glm(PLI.f ~ Distance ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM1b)

logistic.GLM1c <- glm(PLI.f ~ years_since ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM1c)

logistic.GLM1c <- glm(PLI.f ~ CROWN_CLOSURE_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM1c)

logistic.GLM1d <- glm(PLI.f ~ PROJ_AGE_1_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM1d)

logistic.GLM1e <- glm(PLI.f ~ PROJ_HEIGHT_1_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM1e)

logistic.GLM1f <- glm(PLI.f ~ DISTURBANCE_TYPE_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM1f)

logistic.GLM1g <- glm(PLI.f ~ DISTANCE_TO_PERIMETER ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM1g)

logistic.GLM1h <- glm(PLI.f ~ BURN_SEVERITY_RATING_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM1h)
```

```{r}
bin_dis_GIS1$linpred.GLM1a <- predict(logistic.GLM1a) # Estimated logit using the linear part
bin_dis_GIS1$yhat.GLM1a <- fitted(logistic.GLM1a) # Estimated probability using inverse logityhat values
bin_dis_GIS1$resid.GLM1a <- resid(logistic.GLM1a) # the deviances 

# Graph of predicted probabilities ranges for dead versus alive
# Would like the dead=0 (it is alive) trees to have all low predicted prob(dead) 
# and the dead=1 (it is dead) trees to all have high predicted prob (dead). 
par(mfrow=c(1,1),mai=c(1,1,0.6,0.6),cex=0.8)
plot(bin_dis_GIS1$PLI.f,bin_dis_GIS1$yhat.GLM1a,pch=8,
  main="Model 1: Predicted Prob(dead)for Dead versus Alive",
  ylab="Predicted Prob(dead)", xlab="Dead (=1) or Alive (=0) as Recorded")
par(mfrow=c(1,1),mai=c(1,1,1,1),cex=1)
```

```{r}
# GLM1
cutoff <- 0.165 # you can play around with different cutoff values
n <- dim(bin_dis_GIS1)[1]
bin_dis_GIS1$PLI_count_bin <- as.numeric(levels(bin_dis_GIS1$PLI_count_bin))[bin_dis_GIS1$PLI_count_bin]
obs <- bin_dis_GIS1$PLI_count_bin
pred <- ifelse(bin_dis_GIS1$yhat.GLM1a >= cutoff, 1,0)

bin_dis_GIS1$GLM1a <- ifelse( obs == 1 & (obs - pred) == 0, 1, 0) ; a <- sum(bin_dis_GIS1$GLM1a) # a: true positives
bin_dis_GIS1$GLM1c <- ifelse( obs == 1 & (obs - pred) == 1, 1, 0) ; c <- sum(bin_dis_GIS1$GLM1c) # c: false negative
bin_dis_GIS1$GLM1b <- ifelse( obs == 0 & (obs - pred) == -1, 1, 0) ; b <- sum(bin_dis_GIS1$GLM1b) # b: false positives
bin_dis_GIS1$GLM1d <- ifelse( obs == 0 & (obs - pred) == 0, 1, 0) ; d <- sum(bin_dis_GIS1$GLM1d) # d: true negatives

# general confusion matrix layout
matrix(c("a","c" , "b","d"), nrow=2, ncol=2)
CM.GLM1 <- matrix(c(a,c , b,d), nrow=2, ncol=2)
CM.GLM1



# overall accuracy = (a+d)/n
GLM1.oa <- (a+d)/n
GLM1.sensitivity <- a/(a+c)
GLM1.specificity <- d/(b+d)
kappa.bit <- (a+b)*(a+c)+(c+d)*(d+b)
GLM1.kappa <- (  ((a+d)/n)  - (kappa.bit/n^2) ) / (1- (kappa.bit/n^2) )
GLM1.TSS <- GLM1.sensitivity + GLM1.specificity -1

GLM1.predacc <- c(GLM1.oa, GLM1.sensitivity, GLM1.specificity, GLM1.kappa,GLM1.TSS)

GLM1.auc <-pROC::auc(bin_dis_GIS1$PLI_count_bin,bin_dis_GIS1$yhat.GLM1a)
plot(pROC::roc(bin_dis_GIS1$PLI_count_bin,bin_dis_GIS1$yhat.GLM1a),auc.polygon=T)
GLM1a.predacc <- c(GLM1a.oa, GLM1a.sensitivity, GLM1a.specificity, GLM1a.kappa,GLM1a.TSS,GLM1a.auc)
```

```{r}
bin_dis_GIS1$linpred.GLM1a1 <- predict(logistic.GLM1a1) # Estimated logit using the linear part
bin_dis_GIS1$yhat.GLM1a1 <- fitted(logistic.GLM1a1) # Estimated probability using inverse logityhat values
bin_dis_GIS1$resid.GLM1a1 <- resid(logistic.GLM1a1) # the deviances 

cutoff <- 0.8 # you can play around with different cutoff values
n <- dim(bin_dis_GIS1)[1]
obs <- bin_dis_GIS1$PLI_count_bin
pred <- ifelse(bin_dis_GIS1$yhat.GLM1a1 >= cutoff, 1,0)

bin_dis_GIS1$GLM1a <- ifelse( obs == 1 & (obs - pred) == 0, 1, 0) ; a <- sum(bin_dis_GIS1$GLM1a) # a: true positives
bin_dis_GIS1$GLM1c <- ifelse( obs == 1 & (obs - pred) == 1, 1, 0) ; c <- sum(bin_dis_GIS1$GLM1c) # c: false negative
bin_dis_GIS1$GLM1b <- ifelse( obs == 0 & (obs - pred) == -1, 1, 0) ; b <- sum(bin_dis_GIS1$GLM1b) # b: false positives
bin_dis_GIS1$GLM1d <- ifelse( obs == 0 & (obs - pred) == 0, 1, 0) ; d <- sum(bin_dis_GIS1$GLM1d) # d: true negatives

# general confusion matrix layout
matrix(c("a","c" , "b","d"), nrow=2, ncol=2)
CM.GLM1 <- matrix(c(a,c , b,d), nrow=2, ncol=2)
CM.GLM1



# overall accuracy = (a+d)/n
GLM1a1.oa <- (a+d)/n
GLM1a1.sensitivity <- a/(a+c)
GLM1a1.specificity <- d/(b+d)
kappa.bit <- (a+b)*(a+c)+(c+d)*(d+b)
GLM1a1.kappa <- (  ((a+d)/n)  - (kappa.bit/n^2) ) / (1- (kappa.bit/n^2) )
GLM1a1.TSS <- GLM1.sensitivity + GLM1.specificity -1

GLM1.predacc <- c(GLM1.oa, GLM1.sensitivity, GLM1.specificity, GLM1.kappa,GLM1.TSS)

GLM1.auc <-pROC::auc(bin_dis_GIS1$PLI_count_bin,bin_dis_GIS1$yhat.GLM1a1)
plot(pROC::roc(bin_dis_GIS1$PLI_count_bin,bin_dis_GIS1$yhat.GLM1a1),auc.polygon=T)
#GLM1a1.predacc <- c(GLM1a1.oa, GLM1a1.sensitivity, GLM1a1.specificity, GLM1a1.kappa,GLM1a1.TSS,GLM1a1.auc)
```


```{r}
logistic.GLM2a <- glm(FDI.f ~ Distance + years_since + CROWN_CLOSURE_1 + PROJ_AGE_1_1 + 
                        PROJ_HEIGHT_1_1 + DISTURBANCE_TYPE_1 + DISTANCE_TO_PERIMETER + 
                        BURN_SEVERITY_RATING_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM2a)

logistic.GLM2b <- glm(FDI.f ~ Distance ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM2b)

logistic.GLM2c <- glm(FDI.f ~ years_since ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM2c)

logistic.GLM2c <- glm(FDI.f ~ CROWN_CLOSURE_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM2c)

logistic.GLM2d <- glm(FDI.f ~ PROJ_AGE_1_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM2d)

logistic.GLM2e <- glm(FDI.f ~ PROJ_HEIGHT_1_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM2e)

logistic.GLM2f <- glm(FDI.f ~ DISTURBANCE_TYPE_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM2f)

logistic.GLM2g <- glm(FDI.f ~ DISTANCE_TO_PERIMETER ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM2g)

logistic.GLM2h <- glm(FDI.f ~ BURN_SEVERITY_RATING_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.GLM2h)
```
```{r}
bin_dis_GIS1$linpred.GLM2a <- predict(logistic.GLM2a) # Estimated logit using the linear part
bin_dis_GIS1$yhat.GLM2a <- fitted(logistic.GLM2a) # Estimated probability using inverse logityhat values
bin_dis_GIS1$resid.GLM2a <- resid(logistic.GLM2a) # the deviances 

dim(bin_dis_GIS1)
names(bin_dis_GIS1)
head(bin_dis_GIS1) # Notice that the yhat.GLM1 values are bounded by 0 and 1 (are probabilities!)

# Graph of predicted probabilities ranges for dead versus alive
# Would like the dead=0 (it is alive) trees to have all low predicted prob(dead) 
# and the dead=1 (it is dead) trees to all have high predicted prob (dead). 
par(mfrow=c(1,1),mai=c(1,1,0.6,0.6),cex=0.8)
plot(bin_dis_GIS1$FDI.f,bin_dis_GIS1$yhat.GLM2a,pch=8,
  main="Model 1: Predicted Prob(dead)for Dead versus Alive",
  ylab="Predicted Prob(dead)", xlab="Dead (=1) or Alive (=0) as Recorded")
par(mfrow=c(1,1),mai=c(1,1,1,1),cex=1)
```
