---
title: "Occurrence"
author: "Nat"
date: "2024-03-11"
output: html_document
---

# Load dataframes and packages

```{r}
#okay so there is an issue here after all because these tokens are changing
library(tidyverse)
regen <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/Regen_2023_ALL.csv"
regen <- read.csv(regen)
site <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/Site.csv"
site <- read.csv(site)
GIS <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Dataframes/GIS_fixed.csv"
GIS <- read.csv(GIS)
internal <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/Internal.csv"
internal <- read.csv(internal)
basal <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/BasalArea.csv"
basal <- read.csv(basal)
regen_GIS <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Dataframes/regen_GIS.csv"
regen_GIS <- read.csv(regen_GIS)
bin_GIS <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Dataframes/binary_GIS.csv"
bin_GIS <- read.csv(bin_GIS)
regen_binary <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Dataframes/regen_binary.csv"
regen_binary <- read.csv(regen_binary)
actual_coords <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/Plot_coordinates_actual.csv"
actual_coords <- read.csv(actual_coords)
fire_severity <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Dataframes/FireSeverity.csv"
fire_severity <- read.csv(fire_severity)

```
# Looking at wedge data (Bianca said this isnt useful)
```{r}
#Wedges###############################
# now i want to have columns for each species
regen_wedge <- regen
regen_wedge$FDI_total <- ifelse(regen_wedge$Species == "FDI", regen_wedge$total, 0)
regen_wedge$FDI_x0 <- ifelse(regen_wedge$Species == "FDI", regen_wedge$x0, 0)
regen_wedge$FDI_x10 <- ifelse(regen_wedge$Species == "FDI", regen_wedge$x10, 0)
regen_wedge$FDI_x30 <- ifelse(regen_wedge$Species == "FDI", regen_wedge$x30, 0)
regen_wedge$FDI_x130 <- ifelse(regen_wedge$Species == "FDI", regen_wedge$x130, 0)
regen_wedge$PLI_total <- ifelse(regen_wedge$Species == "PLI", regen_wedge$total, 0)
regen_wedge$PLI_x0 <- ifelse(regen_wedge$Species == "PLI", regen_wedge$x0, 0)
regen_wedge$PLI_x10 <- ifelse(regen_wedge$Species == "PLI", regen_wedge$x10, 0)
regen_wedge$PLI_x30 <- ifelse(regen_wedge$Species == "PLI", regen_wedge$x30, 0)
regen_wedge$PLI_x130 <- ifelse(regen_wedge$Species == "PLI", regen_wedge$x130, 0)
regen_wedge$AT_total <- ifelse(regen_wedge$Species == "AT", regen_wedge$total, 0)
regen_wedge$AT_x0 <- ifelse(regen_wedge$Species == "AT", regen_wedge$x0, 0)
regen_wedge$AT_x10 <- ifelse(regen_wedge$Species == "AT", regen_wedge$x10, 0)
regen_wedge$AT_x30 <- ifelse(regen_wedge$Species == "AT", regen_wedge$x30, 0)
regen_wedge$AT_x130 <- ifelse(regen_wedge$Species == "AT", regen_wedge$x130, 0)
regen_wedge$SX_total <- ifelse(regen_wedge$Species == "SX", regen_wedge$total, 0)
regen_wedge$SX_x0 <- ifelse(regen_wedge$Species == "SX", regen_wedge$x0, 0)
regen_wedge$SX_x10 <- ifelse(regen_wedge$Species == "SX", regen_wedge$x10, 0)
regen_wedge$SX_x30 <- ifelse(regen_wedge$Species == "SX", regen_wedge$x30, 0)
regen_wedge$SX_x130 <- ifelse(regen_wedge$Species == "SX", regen_wedge$x130, 0)


# remove NR rows for plots that have other species present
regen_wedge <- regen_wedge %>% 
  group_by(Card) %>% 
  mutate(has_nr = any(Species == "NR"), num_rows = n()) %>% 
  filter(num_rows == 1 | !(has_nr & Species == "NR")) %>% 
  select(-has_nr, -num_rows) %>% 
  select(-Plot_Sp)

regen_wedge <- regen_wedge %>% 
  rename("total_x0" = "x0",
         "total_x10" = "x10",
         "total_x30" = "x30",
         "total_x130" = "x130",
         "total_count" = "total")




regen_wedge1 <- regen_wedge %>% 
  group_by(Card, Quandrant) %>% 
  summarize(SpeciesAll = paste(Species, collapse = ", "),
            total_count = sum(total),
            total_tph = total_count*200,
            total_x0 = sum(x0),
            total_x10 = sum(x10),
            total_x30 = sum(x30),
            total_x130 = sum(x130),
            FDI_count = sum(FDI_total),
            FDI_tph = FDI_count*200,
            FDI_x0 = sum(FDI_x0),
            FDI_x10 = sum(FDI_x10),
            FDI_x30 = sum(FDI_x30),
            FDI_x130 = sum(FDI_x130),
            PLI_count = sum(PLI_total),
            PLI_tph = PLI_count*200,
            PLI_x0 = sum(PLI_x0),
            PLI_x10 = sum(PLI_x10),
            PLI_x30 = sum(PLI_x30),
            PLI_x130 = sum(PLI_x130),
            AT_count = sum(AT_total),
            AT_x0 = sum(AT_x0),
            AT_x10 = sum(AT_x10),
            AT_x30 = sum(AT_x30),
            AT_x130 = sum(AT_x130),
            SX_count = sum(SX_total),
            SX_x0 = sum(SX_x0),
            SX_x10 = sum(SX_x10),
            SX_x30 = sum(SX_x30),
            SX_x130 = sum(SX_x130)) %>% 
  ungroup()



test <- regen_wedge1 %>% 
  group_by(Card) %>% 
  summarize(total_sd = sqrt(sum((total_count-sum(total_count)/4)^2)/3),
            PLI_sd = sqrt(sum((PLI_count-sum(PLI_count)/4)^2)/3),
            FDI_sd = sqrt(sum((FDI_count-sum(FDI_count)/4)^2)/3))

options(scipen=999)

test <- test %>%
  gather(key = "Species", value = "SD", total_sd, PLI_sd, FDI_sd)

ggplot(data=test, aes(x = SD, fill = Species)) +
  geom_histogram(position = "dodge", bins = 30, color = "white", alpha = 0.7) +
  facet_wrap(~Species) +
  theme_minimal() +
  labs(x="SD (Seedlings per plot)", y="Frequency", title="In Plot Variability") +
  scale_fill_discrete()

ggplot(data=filter(test, SD > 0), aes(x = SD, fill = Species)) +
  geom_histogram(position = "dodge", bins = 30, color = "white", alpha = 0.7) +
  facet_wrap(~Species) +
  theme_minimal() +
  labs(x="SD (Seedlings per plot)", y="Frequency", title="In Plot Variability") +
  scale_fill_discrete()

options(scipen=0)

```



# Occurrence as binary plot

```{r}

names(regen_binary)
regen_for_table <- regen_binary %>% 
  summarise(total_no_occurrence = n()-sum(total_count_bin),
            x0_no_occurrence = n()-sum(total_x0_bin),
            x10_no_occurrence = n()-sum(total_x10_bin),
            x30_no_occurrence = n()-sum(total_x30_bin),
            x130_no_occurrence = n()-sum(total_x130_bin),
            FDI_count_occurrence = sum(FDI_count_bin),
            FDI_x0_occurrence = sum(FDI_x0_bin),
            FDI_x10_occurrence = sum(FDI_x10_bin),
            FDI_x30_occurrence = sum(FDI_x30_bin),
            FDI_x130_occurrence = sum(FDI_x130_bin),
            PLI_count_occurrence = sum(PLI_count_bin),
            PLI_x0_occurrence = sum(PLI_x0_bin),
            PLI_x10_occurrence = sum(PLI_x10_bin),
            PLI_x30_occurrence = sum(PLI_x30_bin),
            PLI_x130_occurrence = sum(PLI_x130_bin),
            AT_count_occurrence = sum(AT_count_bin),
            AT_x0_occurrence = sum(AT_x0_bin),
            AT_x10_occurrence = sum(AT_x10_bin),
            AT_x30_occurrence = sum(AT_x30_bin),
            AT_x130_occurrence = sum(AT_x130_bin),
            SX_count_occurrence = sum(SX_count_bin),
            SX_x0_occurrence = sum(SX_x0_bin),
            SX_x10_occurrence = sum(SX_x10_bin),
            SX_x30_occurrence = sum(SX_x30_bin),
            SX_x130_occurrence = sum(SX_x130_bin)
            )

```

```{r}
regen_table <- gather(regen_for_table, "AgeClass", "Count",1:25)
regen_table$Species <- c("No Regen","No Regen","No Regen","No Regen","No Regen","FDI","FDI",
                         "FDI","FDI","FDI","PLI","PLI","PLI","PLI","PLI","Non Conifer",
                         "Non Conifer","Non Conifer","Non Conifer","Non Conifer", 
                         "Spruce","Spruce","Spruce","Spruce", "Spruce")
regen_table$AgeClass <- c("All heights", "x0", "x10", "x30", "x130",
                          "All heights", "x0", "x10", "x30", "x130",
                          "All heights", "x0", "x10", "x30", "x130",
                          "All heights", "x0", "x10", "x30", "x130",
                          "All heights", "x0", "x10", "x30", "x130")

class_order <- c("All heights", "x0", "x10", "x30", "x130")
species_order <- c("PLI","FDI","SX","Non Conifer","No Regen")
ggplot(regen_table, aes(x = factor(AgeClass, levels = class_order), y = Count)) +
  geom_col(aes(fill = factor(Species, levels = species_order)), position = "dodge") +
  xlab("Height Class (cm)") +
  ylab("# of Plots with Occurrence") +
  ggtitle("Occurrence of Regen by Height Class and Species") +
  labs(fill = "Species") +
  scale_fill_brewer(palette = "Spectral") +
  scale_x_discrete(labels = c("total" = "All heights", "x0" = "0-9", "x10" = "10-29", "x30" = "30-129", "x130" = "130+")) +
  theme_bw() +
  theme(axis.text.x=element_text(size=15),
        axis.text.y=element_text(size=15),
        axis.title.x=element_text(size=20),
        axis.title.y=element_text(size=20),
        plot.title = element_text(size = 20),
        legend.text = element_text(size=15),
        legend.title = element_text(size=20))
```



I want to make a graph that has an explanatory categorical variable on the x axis and counts of plots on the y axis. Each category will have 2 bars, one for 0s one for 1s







