---
title: "pivot longer"
author: "Nat"
date: "2024-05-16"
output: html_document
---

```{r}
library(tidyverse)
regen <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/Regen_2023_ALL.csv"
regen <- read.csv("https://raw.githubusercontent.com/nmac2000/Regen/main/Data/Regen_2023_ALL.csv")
site <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/Site.csv"
site <- read.csv(site)
GIS <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Dataframes/GIS_fixed.csv"
GIS <- read.csv(GIS)
internal <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/Internal.csv"
internal <- read.csv(internal)
basal <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/BasalArea.csv"
basal <- read.csv(basal)
regen_GIS <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Dataframes/regen_GIS.csv"
regen_GIS <- read.csv(regen_GIS)
bin_GIS <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Dataframes/binary_GIS.csv"
bin_GIS <- read.csv(bin_GIS)
regen_binary <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Dataframes/regen_binary.csv"
regen_binary <- read.csv(regen_binary)
actual_coords <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/Plot_coordinates_actual.csv"
actual_coords <- read.csv(actual_coords)
distance <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/distance.csv"
distance <- read.csv(distance)
regen <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Data/Regen_2023_ALL.csv"
regen <- read.csv(regen)
fire_severity <- "https://raw.githubusercontent.com/nmac2000/Regen/main/Dataframes/FireSeverity.csv"
fire_severity <- read.csv(fire_severity)
```


```{r}
# Fill in blank species, NR = no regen
regen$Species <- sub("^$", "NR", regen$Species)
regen$Species <- sub("ACT", "NonCon", regen$Species)
regen$Species <- sub("AT", "NonCon", regen$Species)
regen$Species <- sub("SW", "SX", regen$Species)
regen$Species <- sub("SE", "SX", regen$Species)
regen$Species <- sub("SX", "SX", regen$Species)


# get rid of unnecessary columns
regen<- regen %>% 
  select(Card,Quandrant,Species,Notes,x0,x10,x30,x130) 

# new column for species by plot
regen$Plot_Sp <- paste(regen$Card, regen$Species, sep = "")

#new column for total of seedlings per wedge by species
regen<- regen%>% 
  mutate(total = rowSums(cbind(regen$x0,regen$x10,regen$x30,regen$x130),na.rm=TRUE))

#combine different wedges by height class

regen_only_total <- regen %>% 
  group_by(Card, Species, Plot_Sp) %>% 
  summarise(across(total, sum))

regen_only_x0 <- regen %>% 
  group_by(Plot_Sp) %>% 
  summarise(x0 = sum(x0, na.rm = TRUE))

regen_only_x10 <- regen %>% 
  group_by(Plot_Sp) %>% 
  summarise(x10 = sum(x10, na.rm = TRUE))

regen_only_x30 <- regen %>% 
  group_by(Plot_Sp) %>% 
  summarise(x30 = sum(x30, na.rm = TRUE))

regen_only_x130 <- regen %>% 
  group_by(Plot_Sp) %>% 
  summarise(x130 = sum(x130, na.rm = TRUE))

#combine into 1 data frame

regen_all <- full_join(regen_only_total, regen_only_x0, by = "Plot_Sp") %>% 
  full_join(regen_only_x10, by = "Plot_Sp") %>% 
  full_join(regen_only_x30, by = "Plot_Sp") %>%
  full_join(regen_only_x130, by = "Plot_Sp")

```

```{r}
regen_all <- rename(regen_all, SampleSite_ID = "Card")
regen_all_long <- select(regen_all, SampleSite_ID:x130)
regen_longer_GIS <- full_join(regen_all_long, GIS, by = "SampleSite_ID")

#distance <- rename(distance, SampleSite_ID = "Card")
regen_longer_GIS <- full_join(regen_longer_GIS, distance, by = "SampleSite_ID")
#write.csv(regen_longer_GIS,  "C:/Users/nmac2000/Documents/regen project/Regen/Data/Longer_regen.csv")
regen_longer_GIS$years_since <- 2023-regen_longer_GIS$FIRE_YEAR_1
regen_longer_GIS$years_since <- as.factor(regen_longer_GIS$years_since)
regen_longer_GIS <- regen_longer_GIS %>% 
  filter(!is.na(Species),
         Species != "NR") 
```

```{r}
ggplot(filter(regen_longer_GIS), aes(x=Distance, y=total)) +
  geom_point(aes(colour = Species), alpha=0.8, size=1) +
  geom_smooth(aes(colour = Species), method="loess", se=FALSE)

ggplot(regen_longer_GIS, aes(x=years_since, y=total)) +
  geom_boxplot(aes(fill = Species))+
  theme_minimal()

ggplot(regen_longer_GIS, aes(x=SPECIES_CD_1_1, y=total)) +
  geom_boxplot(aes(fill = Species))+
  theme_minimal()
regen_longer_GIS$CROWN_CLOSURE_1 <- as.factor(regen_longer_GIS$CROWN_CLOSURE_1)
ggplot(regen_longer_GIS, aes(x=CROWN_CLOSURE_1, y=total)) +
  geom_boxplot()+
  facet_wrap(~Species) +
  theme_minimal()
```
#now graphs with occurrence instead
```{r}
regen_binary <- rename(regen_binary, SampleSite_ID = "Card")
#distance <- rename(distance, SampleSite_ID = "Card")
regen_binary_distance <- left_join(distance, regen_binary, by = "SampleSite_ID")
bin_dis_GIS <- left_join(regen_binary_distance, GIS, by = "SampleSite_ID")
#fire_severity <- rename(fire_severity, SampleSite_ID = "Card")
bin_dis_GIS <- left_join(bin_dis_GIS, fire_severity)

bin_dis_GIS <- left_join(bin_dis_GIS, BARC)
bin_dis_GIS$years_since <- as.factor(2023-bin_dis_GIS$FIRE_YEAR_1)
bin_dis_GIS$FDI_count_bin <- as.factor(bin_dis_GIS$FDI_count_bin)
bin_dis_GIS$PLI_count_bin <- as.factor(bin_dis_GIS$PLI_count_bin)
bin_dis_GIS$SX_count_bin <- as.factor(bin_dis_GIS$SX_count_bin)
bin_dis_GIS <- filter(bin_dis_GIS, !is.na(SPECIES_CD_1_1))

BARC <- read.csv("https://raw.githubusercontent.com/nmac2000/Regen/main/Data/BARC.csv")
BARC <- BARC %>% 
  select(Card, MEAN) %>% 
  mutate(BARC = round(MEAN)) %>% 
  rename(SampleSite_ID = "Card")
bin_dis_GIS <- left_join(bin_dis_GIS, BARC, by = "SampleSite_ID")
```

```{r}
filtered_data <- filter(bin_dis_GIS, !is.na(FDI_count_bin))

# Create the plot
ggplot(filtered_data, aes(x = FDI_count_bin, y = Distance)) +
  geom_boxplot(aes(group = FDI_count_bin, fill = as.factor(FDI_count_bin))) +
  facet_wrap(~ SPECIES_CD_1_1, scales = "free_y") +
  labs(title = "Distance by FDI Count Bin across Species",
       x = "FDI Count Bin",
       y = "Distance",
       fill = "FDI Count Bin",
       color = "FDI Count Bin") +
  theme_minimal() +
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5)) +
  scale_color_brewer(palette = "Set3") +
  scale_fill_brewer(palette = "Set3")

ggplot(filter(bin_dis_GIS, !is.na(FDI_count_bin)), aes(x=FDI_count_bin, y= Distance)) +
  geom_boxplot(aes(group = FDI_count_bin))


ggplot(filter(bin_dis_GIS, !is.na(PLI_count_bin)), aes(x=PLI_count_bin, y= Distance)) +
  geom_boxplot(aes(group = PLI_count_bin)) 

ggplot(filtered_data, aes(x = PLI_count_bin, y = Distance)) +
  geom_boxplot(aes(group = PLI_count_bin, fill = as.factor(PLI_count_bin))) +
  facet_wrap(~ SPECIES_CD_1_1, scales = "free_y") +
  labs(title = "Distance by PLI Count Bin across Species",
       x = "PLI Count Bin",
       y = "Distance",
       fill = "PLI Count Bin",
       color = "PLI Count Bin") +
  theme_minimal() +
  theme(legend.position = "bottom",
        plot.title = element_text(hjust = 0.5)) +
  scale_color_brewer(palette = "Set3") +
  scale_fill_brewer(palette = "Set3")


ggplot(filter(bin_dis_GIS, !is.na(SX_count_bin)), aes(x=SX_count_bin, y= Distance)) +
  geom_boxplot()
```
```{r}

ggplot(filter(bin_dis_GIS, !is.na(FDI_count_bin)), aes(x=FDI_count_bin, y= PROJ_AGE_1_1)) +
  geom_boxplot(aes(group = FDI_count_bin)) +
  facet_wrap(~ SPECIES_CD_1_1)

ggplot(filter(bin_dis_GIS, !is.na(PLI_count_bin)), aes(x=PLI_count_bin, y= PROJ_AGE_1_1)) +
  geom_boxplot(aes(group = PLI_count_bin))+
  facet_wrap(~ SPECIES_CD_1_1)

ggplot(filter(bin_dis_GIS, !is.na(SX_count_bin)), aes(x=SX_count_bin, y= PROJ_AGE_1_1)) +
  geom_boxplot(aes(group = SX_count_bin))+
  facet_wrap(~ SPECIES_CD_1_1)
```
```{r}

ggplot(filter(bin_dis_GIS, !is.na(FDI_count_bin)), aes(x=FDI_count_bin, y= CROWN_CLOSURE_1)) +
  geom_boxplot(aes(group = FDI_count_bin))+
  facet_wrap(~ SPECIES_CD_1_1)

ggplot(filter(bin_dis_GIS, !is.na(PLI_count_bin)), aes(x=PLI_count_bin, y= CROWN_CLOSURE_1)) +
  geom_boxplot(aes(group = PLI_count_bin))+
  facet_wrap(~ SPECIES_CD_1_1)

ggplot(filter(bin_dis_GIS, !is.na(SX_count_bin)), aes(x=SX_count_bin, y= CROWN_CLOSURE_1)) +
  geom_boxplot(aes(group = SX_count_bin))+
  facet_wrap(~ SPECIES_CD_1_1)
```
```{r}


mosaicplot(~ FDI_count_bin + SPECIES_CD_1_1, 
           data = bin_dis_GIS, 
           color = TRUE, 
           main = "Mosaic Plot of FDI Occurrence by Dominant Overstory Species", 
           xlab = "Seedling Occurrence", 
           ylab = "Species Code",
           las = 2, # Rotate the axis labels for better readability
           cex.axis = 0.8) # Adjust axis label size

mosaicplot(~ PLI_count_bin + SPECIES_CD_1_1, 
           data = bin_dis_GIS, 
           color = TRUE, 
           main = "Mosaic Plot of PLI Occurrence by Dominant Overstory Species", 
           xlab = "Seedling Occurrence", 
           ylab = "Species Code",
           las = 2, # Rotate the axis labels for better readability
           cex.axis = 0.8) # Adjust axis label size

mosaicplot(~ SX_count_bin + SPECIES_CD_1_1, 
           data = bin_dis_GIS, 
           color = TRUE, 
           main = "Mosaic Plot of SX Occurrence by Dominant Overstory Species", 
           xlab = "Seedling Occurrence", 
           ylab = "Species Code",
           las = 2, # Rotate the axis labels for better readability
           cex.axis = 0.8) # Adjust axis label size
```

```{r}
#PLISTOP
ggplot(filter(bin_dis_GIS, !is.na(PLI_count_bin)), aes(x=PLI_count_bin, y=Distance)) +
  geom_boxplot(aes(group = PLI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Distance to nearest live tree by PLI seedling Occurrence",
    x = "PLI Occurrence",
    y = "Distance (m)",
  ) +
  theme_minimal()

ggplot(filter(bin_dis_GIS, !is.na(PLI_count_bin)), aes(x=PLI_count_bin, y= years_since)) +
  geom_boxplot(aes(group = PLI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Years since fire by PLI seedling Occurrence",
    x = "PLI Occurrence",
    y = "Years",
  ) +
  theme_minimal()

ggplot(filter(bin_dis_GIS, !is.na(PLI_count_bin)), aes(x=PLI_count_bin, y= PROJ_HEIGHT_1_1)) +
  geom_boxplot(aes(group = PLI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Pre-fire stand projected height by PLI seedling Occurrence",
    x = "PLI Occurrence",
    y = "Projected height (m)",
  ) +
  theme_minimal()

ggplot(filter(bin_dis_GIS, !is.na(PLI_count_bin)), aes(x=PLI_count_bin, y= DISTANCE_TO_PERIMETER)) +
  geom_boxplot(aes(group = PLI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Distance to burn perimeter by PLI seedling Occurrence",
    x = "PLI Occurrence",
    y = "Distance (m)",
  ) +
  theme_minimal()

ggplot(filter(bin_dis_GIS, !is.na(PLI_count_bin)), aes(x=PLI_count_bin, y= MEAN)) +
  geom_boxplot(aes(group = PLI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Burn Severity by PLI seedling Occurrence",
    x = "PLI Occurrence",
    y = "nDBR",
  ) +
  theme_minimal()

ggplot(filter(bin_dis_GIS, !is.na(PLI_count_bin)), aes(x=PLI_count_bin, y= CROWN_CLOSURE_1)) +
  geom_boxplot(aes(group = PLI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Pre-fire crown closure by PLI seedling Occurrence",
    x = "PLI Occurrence",
    y = "Crown CLosure (%)",
  ) +
  theme_minimal()

ggplot(filter(bin_dis_GIS, !is.na(PLI_count_bin)), aes(x=PLI_count_bin, y= PROJ_AGE_1_1)) +
  geom_boxplot(aes(group = PLI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Pre-fire projected age by PLI seedling Occurrence",
    x = "PLI Occurrence",
    y = "Age (years)",
  ) +
  theme_minimal()

ggplot(filter(bin_dis_GIS, !is.na(PLI_count_bin)), aes(x=PLI_count_bin, y= PATCH_SIZE_1)) +
  geom_boxplot(aes(group = PLI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Fire Severity patch size by PLI seedling Occurrence",
    x = "PLI Occurrence",
    y = "Patch size (?)",
  ) +
  theme_minimal()

mosaicplot(~ PLI_count_bin + SPECIES_CD_1_1, 
           data = bin_dis_GIS, 
           color = TRUE, 
           main = "PLI Occurrence by Dominant Overstory Species", 
           xlab = "Seedling Occurrence", 
           ylab = "Species Code",
           las = 2, # Rotate the axis labels for better readability
           cex.axis = 0.8) # Adjust axis label size

mosaicplot(~ PLI_count_bin + DISTURBANCE_TYPE_1, 
           data = bin_dis_GIS1, 
           color = TRUE, 
           main = "PLI Occurrence by Pre-fire Disturbance", 
           xlab = "Seedling Occurrence", 
           ylab = "Disturbance Code",
           las = 2, # Rotate the axis labels for better readability
           cex.axis = 0.8) # Adjust axis label size

mosaicplot(~ PLI_count_bin + BURN_SEVERITY_RATING_1, 
           data = bin_dis_GIS1, 
           color = TRUE, 
           main = "PLI Occurrence by Burn Severity", 
           xlab = "Seedling Occurrence", 
           ylab = "Severity",
           las = 2, # Rotate the axis labels for better readability
           cex.axis = 0.8) # Adjust axis label size
#PLISTOP
```
```{r}
ggplot(filter(bin_dis_GIS, !is.na(FDI_count_bin)), aes(x=FDI_count_bin, y=Distance)) +
  geom_boxplot(aes(group = FDI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Distance to nearest live tree by FDI seedling Occurrence",
    x = "FDI Occurrence",
    y = "Distance (m)",
  ) +
  theme_minimal()

ggplot(filter(bin_dis_GIS, !is.na(FDI_count_bin)), aes(x=FDI_count_bin, y= years_since)) +
  geom_boxplot(aes(group = FDI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Years since fire by FDI seedling Occurrence",
    x = "FDI Occurrence",
    y = "Years",
  ) +
  theme_minimal()

ggplot(filter(bin_dis_GIS, !is.na(FDI_count_bin)), aes(x=FDI_count_bin, y= PROJ_HEIGHT_1_1)) +
  geom_boxplot(aes(group = FDI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Pre-fire stand projected height by FDI seedling Occurrence",
    x = "FDI Occurrence",
    y = "Projected height (m)",
  ) +
  theme_minimal()

ggplot(filter(bin_dis_GIS, !is.na(FDI_count_bin)), aes(x=FDI_count_bin, y= DISTANCE_TO_PERIMETER)) +
  geom_boxplot(aes(group = FDI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Distance to burn perimeter by FDI seedling Occurrence",
    x = "FDI Occurrence",
    y = "Distance (m)",
  ) +
  theme_minimal()

ggplot(filter(bin_dis_GIS1, !is.na(FDI_count_bin)), aes(x=FDI_count_bin, y= MEAN)) +
  geom_boxplot(aes(group = FDI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Burn Severity by FDI seedling Occurrence",
    x = "FDI Occurrence",
    y = "nDBR",
  ) +
  theme_minimal()

ggplot(filter(bin_dis_GIS, !is.na(FDI_count_bin)), aes(x=FDI_count_bin, y= CROWN_CLOSURE_1)) +
  geom_boxplot(aes(group = FDI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Pre-fire crown closure by FDI seedling Occurrence",
    x = "FDI Occurrence",
    y = "Crown CLosure (%)",
  ) +
  theme_minimal()

ggplot(filter(bin_dis_GIS, !is.na(FDI_count_bin)), aes(x=FDI_count_bin, y= PROJ_AGE_1_1)) +
  geom_boxplot(aes(group = FDI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Pre-fire projected age by FDI seedling Occurrence",
    x = "FDI Occurrence",
    y = "Age (years)",
  ) +
  theme_minimal()

ggplot(filter(bin_dis_GIS, !is.na(FDI_count_bin)), aes(x=FDI_count_bin, y= PATCH_SIZE_1)) +
  geom_boxplot(aes(group = FDI_count_bin), fill = "skyblue", color = "darkblue", outlier.color = "red") +
  labs(
    title = "Fire Severity patch size by FDI seedling Occurrence",
    x = "FDI Occurrence",
    y = "Patch size (?)",
  ) +
  theme_minimal()

mosaicplot(~ FDI_count_bin + SPECIES_CD_1_1, 
           data = bin_dis_GIS, 
           color = TRUE, 
           main = "FDI Occurrence by Dominant Overstory Species", 
           xlab = "Seedling Occurrence", 
           ylab = "Species Code",
           las = 2, # Rotate the axis labels for better readability
           cex.axis = 0.8) # Adjust axis label size

mosaicplot(~ FDI_count_bin + DISTURBANCE_TYPE_1, 
           data = bin_dis_GIS1, 
           color = TRUE, 
           main = "FDI Occurrence by Pre-fire Disturbance", 
           xlab = "Seedling Occurrence", 
           ylab = "Disturbance Code",
           las = 2, # Rotate the axis labels for better readability
           cex.axis = 0.8) # Adjust axis label size

mosaicplot(~ PLI_count_bin + BARC.x, 
           data = bin_dis_GIS1, 
           color = TRUE, 
           main = "FDI Occurrence by Burn Severity", 
           xlab = "Seedling Occurrence", 
           ylab = "Severity",
           las = 2, # Rotate the axis labels for better readability
           cex.axis = 0.8) # Adjust axis label size

ggplot(bin_dis_GIS1, aes(x=BARC.x, y=MEAN)) +
  geom_boxplot(fill = "skyblue", color = "darkblue", outlier.color = "red") +
  geom_jitter(position=position_jitter(height=0, width=0.3)) +
#  facet_wrap(vars(FIRE_NUMBER_1)) +
  labs(
    title = "Fire Severity",
    x = "Fire Severity",
    y = "dNBR",
  ) +
  theme_minimal()

ggplot(bin_dis_GIS1, aes(x=BURN_SEVERITY_RATING_1, y=MEAN)) +
  geom_boxplot(fill = "skyblue", color = "darkblue", outlier.color = "red") +
  geom_point() +
#  facet_wrap(vars(FIRE_NUMBER_1)) +
  labs(
    title = "Fire Severity",
    x = "Fire Severity",
    y = "dNBR",
  ) +
  theme_minimal()

idk <- left_join(distance, regen_GIS1, by = "SampleSite_ID")
idk <- idk %>% 
  distinct(SampleSite_ID, .keep_all = T)

ggplot(idk, aes(x=SOILNAME_1, y=FDI_count)) +
  geom_boxplot(fill = "skyblue", color = "darkblue", outlier.color = "red") +
  geom_point() +
#  facet_wrap(vars(FIRE_NUMBER_1)) +
  labs(
    title = "FDI Seedling Occurrence by Soil Type",
    x = "Soil Type",
    y = "Count",
    las = 2
  ) +
  theme(axis.text.x = element_text(angle = -90, hjust = 1, vjust = 0.5))

bin_dis_GIS1 %>% 
#  filter(SOILNAME_1 == "NO SOILS DATA") %>%
  group_by(PLI_count_bin) %>% 
  summarize(count=n())

```
```{r}
bin_dis_GIS1$BARC.x <- bin_dis_GIS1$BARC.y 

bin_dis_GIS1 <- within(bin_dis_GIS1, {   
  BARC.x <- NA # need to initialize variable
  BARC.x[MEAN < .105] <- "1"
  BARC.x[MEAN >= .105 & MEAN < 0.275] <- "2"
  BARC.x[MEAN >= 0.275 & MEAN < 0.66] <- "3"
  BARC.x[MEAN >= 0.66] <- 4
   } )

bin_dis_GIS1 <- within(bin_dis_GIS1, {   
  BARC.z <- NA # need to initialize variable
  BARC.z[MAX < .105] <- "1"
  BARC.z[MAX >= .105 & MAX < 0.275] <- "2"
  BARC.z[MAX >= 0.275 & MAX < 0.66] <- "3"
  BARC.z[MAX >= 0.66] <- 4
   } )

bin_dis_GIS1$BARC.z <- as.factor(bin_dis_GIS1$BARC.z)

ggplot(bin_dis_GIS1, aes(x=BARC.x, y=MEAN)) +
  geom_boxplot(fill = "skyblue", color = "darkblue", outlier.color = "red") +
  geom_jitter(position=position_jitter(height=0, width=0.35)) +
#  facet_wrap(vars(FIRE_NUMBER_1)) +
  labs(
    title = "Fire Severity",
    x = "Fire Severity",
    y = "dNBR",
  ) +
  theme_minimal()

filter(bin_dis_GIS1, BARC.z == 4)
```
# Summary Tables
```{r}
bin_dis_GIS1 %>% 
#  select(BARC.y, PLI_count_bin, FDI_count_bin) %>% 
  filter(FDI_count_bin == 1) %>% 
  group_by(FIRE_NUMBER_1 ) %>% 
  summarize(count = n())

for_summary <- regen_longer_GIS %>% 
  filter(SampleSite_ID %in% bin_dis_GIS1$SampleSite_ID)

for_summary %>% 
  filter(SampleSite_ID %in% bin_dis_GIS1$SampleSite_ID)


for_summary %>% 
  group_by(Species) %>% 
  summarise(total = sd(x30))

bin_dis_GIS1 %>%  
  filter(SX_count_bin == 1) %>% 
  summarize(count = n())


for_summary1 <- regen %>% 
  filter(Card %in% bin_dis_GIS1$SampleSite_ID) %>% 
  ungroup

quadrant_order <- c("NE", "SE", "SW", "NW")

for_summary1$total <- rowSums(for_summary1[, c("x0", "x10", "x30", "x130")], na.rm=T)




SX_mean <- for_summary1 %>% 
  filter(Species == "SX") %>% 
  mutate(Quandrant = factor(Quandrant, levels = quadrant_order)) %>%
  group_by(Quandrant) %>% 
  summarize(sum = sum(total, na.rm = TRUE),
            mean = round(sum/39, 3))

for_summary1 %>% 
  filter(Species == "SX",
         !is.na(total)) %>% 
  group_by(Card) %>% 
  summarize(sum = n()) %>% 
  ungroup() 

  summarize(sd = sqrt((sum(total-mean(total, na.rm = T), na.rm = T)^2)/38),
            sd1 = sd(total, na.rm = T),
            mean = mean(total, na.rm = T))

SX_n <- bin_dis_GIS1 %>%  
  filter(SX_count_bin == 1) %>% 
  summarize(count = n())
SX_n <- as.list(SX_n[1])

SX_NE_mean <- SX_mean$mean[1]

SX_NE_total <- for_summary1 %>% 
  filter(Species == "SX",
         Quandrant == "NE",
         !is.na(total))
SX_NE_total <- as.list(SX_NE_total$total)

sqrt(sum(across((SX_NE_total-SX_NE_mean))^2/SX_n))
  
# pull samplesite_id for each species from where i got total plots with species present and then turn the NA's into zeros 
# for summary_1 and filter by the samplesite_id and then find the means

for_summary1 <- for_summary1 %>% 
  select(-Notes, -x) %>% 
  mutate(across(everything(), .fns = ~replace_na(.,0)))   
  
SX_n <- bin_dis_GIS1 %>%  
  filter(SX_count_bin == 1) 

FDI_n <- bin_dis_GIS1 %>%  
  filter(FDI_count_bin == 1) 

AT_n <- bin_dis_GIS1 %>%  
  filter(NonCon_count_bin == 1) 

PLI_n <- bin_dis_GIS1 %>%  
  filter(PLI_count_bin == 1) 


for_summary1 %>% 
  filter(Card %in% SX_n$SampleSite_ID,
         Species == "SX") %>% 
  complete(Card, Quandrant = c("NE", "SE", "NW", "SW"), 
           fill = list(Species = "SX", x0 = 0, x10 = 0, x30 = 0, x130 = 0, total = 0)) %>% 
  mutate(Quandrant = factor(Quandrant, levels = quadrant_order)) %>%
  group_by(Card) %>% 
  summarise(count = sum(total), mean = round(mean(total), 3), sd = round(sd(total), 3))

bin_dis_GIS1 %>% 
  filter(is.na(Elevation))

bin_dis_GIS1 %>% 
  select(-X.x, -X.y, -UNIQUE_ID, -Contract ) %>% 
  filter(SampleSite_ID %in% c(270, 407, 413, 417, 540, 1052, 1209, 1401, 1487, 1526, 1560, 1573, 1583, 1592,
                              1594, 1605, 1607, 1617, 1624, 1628, 2251, 2253)) 
  select(BARC.y) %>% 
  table()
  
new_regen <- regen_GIS %>% 
  distinct(SampleSite_ID, .keep_all = T) %>% 
  filter(SampleSite_ID %in% bin_dis_GIS1$SampleSite_ID) 

new_regen$years_since <- bin_dis_GIS1$years_since
new_regen$MEAN.x <- bin_dis_GIS1$MEAN.x
new_regen$MAX <- bin_dis_GIS1$MAX
new_regen$BARC.y <- bin_dis_GIS1$BARC.y

new_regen <- new_regen %>% 
  filter(!SampleSite_ID %in% c(456, 1108, 1422, 1643, 361, 1514))

highlighted_sites <- new_regen %>% 
  filter(SampleSite_ID %in% c(270, 407, 413, 417, 540, 1052, 1209, 1401, 1487, 1526, 1560, 1573, 1583, 1592,
                              1594, 1605, 1607, 1617, 1624, 1628, 2251, 2253)) 
new_regen %>% 
  filter(SPECIES_CD_1_1 != "FDI",
         SPECIES_CD_1_1 != "PLI",
         SPECIES_CD_1_1 != "AT",
         SPECIES_CD_1_1 != "SX")

ggplot(new_regen, aes(x=COFRAG_1, y =FDI_count)) +
  geom_point() +
  geom_point(data = highlighted_sites, color = "darkred", 
             position = position_jitter(width = 0.2))

highlighted_sites1 <- bin_dis_GIS1 %>% 
  filter(SampleSite_ID %in% c(270, 407, 413, 417, 540, 1052, 1209, 1401, 1487, 1526, 1560, 1573, 1583, 1592,
                              1594, 1605, 1607, 1617, 1624, 1628, 2251, 2253)) 

ggplot(bin_dis_GIS1, aes(x=FDI_count_bin, y =DISTANCE_TO_PERIMETER)) +
  geom_boxplot() +
  geom_point(data = highlighted_sites1, color = "darkred", 
             position = position_jitter(width = 0.2))
  

bin_dis_GIS1 %>% 
  filter(!SampleSite_ID %in% not_measured$SampleSite_ID) %>% 
  filter(SPECIES_CD_1_1 == "") %>% 
  select(SampleSite_ID,  PLI_count_bin)

bin_dis_GIS1 %>% 
  filter(SPECIES_CD_1_1 == "") %>% 
#  filter(HARVEST_DATE_1 != "") %>% 
  select(SampleSite_ID, SPECIES_CD_1_1, FIRE_YEAR_1, HARVEST_DATE_1) #%>% 
  mutate(years_since_harvest = FIRE_YEAR_1-lubridate::year(HARVEST_DATE_1)) %>% 
  filter(years_since_harvest > 20)


filter <- bin_dis_GIS1 %>% 
  filter(TEXTURE_1 != "")
table(filter$PARENT_SOILS, filter$TEXTURE_1)
table(bin_dis_GIS1$BEC_Zone, bin_dis_GIS1$BEC_Subzone) 

for_summary1 <- for_summary %>% 
  mutate(totaltph = total*200) %>% 
  mutate(x0tph = x0*200) %>%
  mutate(x10tph = x10*200) %>%
  mutate(x30tph = x30*200) %>%
  mutate(x130tph = x130*200) 
  
for_summary1 %>% 
  group_by(Species) %>% 
  summarise(total = sum(x10tph)/320)

regen_GIS %>% 
  filter(SampleSite_ID %in% bin_dis_GIS1$SampleSite_ID) %>% 
  filter(str_detect(SpeciesAll, "PLI|FDI|SX")) %>% 
  summarise(total = n())

bin_dis_GIS1 %>% 
  group_by(DRAIN_1) %>% 
  summarise(total = n())

bin_dis_GIS1 %>% 
  select(FIRE_YEAR_1, FDI_count_bin, PLI_count_bin) %>% 
  filter(FDI_count_bin == 1 | PLI_count_bin==1) %>% 
  group_by(FIRE_YEAR_1) %>% 
  summarise(total = n())

```




