---
title: "Models2"
author: "Nat"
date: "2024-08-07"
output: html_document
---


```{r}
#need to figure out data frames for everything and clean up code
bin_dis_GIS1 <- bin_dis_GIS %>%
  distinct(SampleSite_ID, .keep_all = T) %>% 
  filter(!SampleSite_ID %in% not_measured$SampleSite_ID) %>% 
  filter(!SampleSite_ID %in% c(456, 496, 1108, 1422, 1514, 1643))

```

structural
```{r}
names(bin_dis_GIS1)  # print out the column (i.e., variable) names
dim(bin_dis_GIS1)    # number of rows and columns
head(bin_dis_GIS1)  # print out the first few lines of data

#need to put this somewhere else later on
bin_dis_GIS1$DISTURBANCE_TYPE_1<- sub( "IBM  ", "IBM", bin_dis_GIS1$DISTURBANCE_TYPE_1)

# ensure y variable is a factor for dead versus alive
bin_dis_GIS1$PLI.f <- as.factor(bin_dis_GIS1$PLI_count_bin)
bin_dis_GIS1$FDI.f <- as.factor(bin_dis_GIS1$FDI_count_bin)
# y=1 for dead trees, y=0 for live trees
class(bin_dis_GIS1$PLI.f)
bin_dis_GIS1$Distance <- as.numeric(bin_dis_GIS1$Distance)
bin_dis_GIS1$CROWN_CLOSURE_1 <- as.numeric(bin_dis_GIS1$CROWN_CLOSURE_1)
bin_dis_GIS1$PROJ_AGE_1_1 <- as.numeric(bin_dis_GIS1$PROJ_AGE_1_1)
bin_dis_GIS1$PROJ_HEIGHT_1_1 <- as.numeric(bin_dis_GIS1$PROJ_HEIGHT_1_1)
bin_dis_GIS1$DISTANCE_TO_PERIMETER <- as.numeric(bin_dis_GIS1$DISTANCE_TO_PERIMETER)
bin_dis_GIS1$years_since <- as.numeric(2023-bin_dis_GIS1$FIRE_YEAR_1)
bin_dis_GIS1$DISTURBANCE_TYPE_1 <- as.factor(bin_dis_GIS1$DISTURBANCE_TYPE_1)
bin_dis_GIS1$BURN_SEVERITY_RATING_1 <- factor(bin_dis_GIS1$BURN_SEVERITY_RATING_1, 
                                                 levels = c("Unburned", "Low", "Medium", "High", "Unknown"))
bin_dis_GIS1$SPECIES_CD_1_1 <- factor(bin_dis_GIS1$SPECIES_CD_1_1, levels = c("PLI", "FDI", "AT", "SX"))
bin_dis_GIS1$BARC.x <- as.factor(bin_dis_GIS1$BARC.x)


#bin_dis_GIS1 <- bin_dis_GIS1 %>% 
  filter(!is.na(Distance), !is.na(years_since), !is.na(CROWN_CLOSURE_1),
         !is.na(PROJ_AGE_1_1), !is.na(PROJ_HEIGHT_1_1), !is.na(DISTURBANCE_TYPE_1),
         !is.na(DISTANCE_TO_PERIMETER), !is.na(BURN_SEVERITY_RATING_1),
         !is.na(PLI.f), !is.na(FDI.f), !is.na(MEAN.y))
```

Step 1
```{r}
structure.PLI.full <- glm(PLI.f ~ Distance + years_since + CROWN_CLOSURE_1 + PROJ_AGE_1_1 + 
                        PROJ_HEIGHT_1_1 + DISTURBANCE_TYPE_1 + DISTANCE_TO_PERIMETER + 
                        BURN_SEVERITY_RATING_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.full)

logistic.null <- glm(PLI.f ~ 1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(logistic.null)

structure.PLIa <- glm(PLI.f ~ Distance ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIa) #not significant on own

structure.PLIb <- glm(PLI.f ~ years_since ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIb) #significant on own

structure.PLIc <- glm(PLI.f ~ CROWN_CLOSURE_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIc) #not significant on own

structure.PLId <- glm(PLI.f ~ PROJ_AGE_1_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLId) #significant on own

structure.PLIe <- glm(PLI.f ~ PROJ_HEIGHT_1_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIe) #significant on own

structure.PLIf <- glm(PLI.f ~ DISTURBANCE_TYPE_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIf) #significant on own 


structure.PLIg <- glm(PLI.f ~ DISTANCE_TO_PERIMETER ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIg) #significant on own

structure.PLIh <- glm(PLI.f ~ BURN_SEVERITY_RATING_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIh) #significant on own

structure.PLIi <- glm(PLI.f ~ MEAN ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIi)

structure.PLIj <- glm(PLI.f ~ SPECIES_CD_1_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIj)

structure.PLIk <- glm(PLI.f ~ PATCH_SIZE_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIk)

structure.PLIl <- glm(PLI.f ~ SPECIES_PCT_1_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIl)

structure.PLIm <- glm(PLI.f ~ SPECIES_CD_2_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIm)

structure.PLIn <- glm(PLI.f ~ SPECIES_CD_3_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIn)

structure.PLIo <- glm(PLI.f ~ BARC.y ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIo)
lrtest(structure.PLIo, logistic.null)

structure.PLIp <- glm(PLI.f ~ BARC.x ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIp)
lrtest(structure.PLIp, logistic.null)

structure.PLIq <- glm(PLI.f ~ BARC.z ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLIq)
lrtest(structure.PLIq, logistic.null)

lrtest(structure.PLIj, logistic.null)
lrtest(structure.PLIm, logistic.null)
lrtest(structure.PLIn, logistic.null)
```
Compare categorical variables to null model
```{r}
library(lmtest)
lrtest(structure.PLIf, logistic.null)
lrtest(structure.PLIh, logistic.null)
```

Step 2 with dNBR
```{r}
structure.PLI.2a <- glm(PLI.f ~ years_since  + MEAN  + SPECIES_CD_1_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2a)
lrtest(structure.PLI.2a, glm(PLI.f ~ years_since  + MEAN,family=binomial(link = "logit"), data=bin_dis_GIS1))

structure.PLI.2b <- glm(PLI.f ~ years_since  + MEAN  + SPECIES_CD_1_1 + SPECIES_CD_2_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2b)
lrtest(structure.PLI.2b, structure.PLI.2a) #restrictions justified, remove SPECIES_CD_2_1

structure.PLI.2c <- glm(PLI.f ~ years_since  + MEAN  + SPECIES_CD_1_1 + SPECIES_CD_3_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2c)
lrtest(structure.PLI.2c, structure.PLI.2a) #restrictions justified, remove SPECIES_CD_3_1

structure.PLI.2d <- glm(PLI.f ~ years_since  + MEAN  + SPECIES_CD_1_1 + PROJ_HEIGHT_1_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2d)
lrtest(structure.PLI.2d, structure.PLI.2a) #restrictions justified, remove PROJ_HEIGHT_1_1

structure.PLI.2e <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2e)
lrtest(structure.PLI.2e, glm(PLI.f ~ years_since , family=binomial(link = "logit"), data=bin_dis_GIS1))

structure.PLI.2f <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1 + SPECIES_CD_2_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2f)
lrtest(structure.PLI.2f, structure.PLI.2e) # restrictions justified, remove SPECIES_CD_2_1

structure.PLI.2g <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1 + PROJ_HEIGHT_1_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2g)
lrtest(structure.PLI.2g, structure.PLI.2e) #restrictions justified, remove PROJ_HEIGHT_1_1

structure.PLI.2h <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1 + DISTANCE_TO_PERIMETER,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2h)
lrtest(structure.PLI.2h, structure.PLI.2e) #restrictions justified, remove DISTANCE_TO_PERIMETER

structure.PLI.2i <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1 + PATCH_SIZE_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2i)
lrtest(structure.PLI.2i, structure.PLI.2e) #restrictions justified, remove PATCH_SIZE_1

structure.PLI.2j <- glm(PLI.f ~ years_since  + MEAN  + SPECIES_CD_1_1 + DISTANCE_TO_PERIMETER,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2j)
lrtest(structure.PLI.2j, structure.PLI.2a) #restrictions justified, remove DISTANCE_TO_PERIMETER

structure.PLI.2k <- glm(PLI.f ~ years_since  + MEAN  + SPECIES_CD_1_1 + PATCH_SIZE_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2k)
lrtest(structure.PLI.2k, structure.PLI.2a) #restrictions justified, remove PATCH_SIZE_1

structure.PLI.2l <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1 + BURN_SEVERITY_RATING_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2l)
lrtest(structure.PLI.2l, structure.PLI.2e) #restrictions justified, remove BURN_SEVERITY_RATING_1

structure.PLI.2m <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1 + BURN_SEVERITY_RATING_1 +MEAN,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2m)
lrtest(structure.PLI.2m, structure.PLI.2a) #restrictions justified, remove BURN_SEVERITY_RATING_1

structure.PLI.2n <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1 + DISTURBANCE_TYPE_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2n)
lrtest(structure.PLI.2n, structure.PLI.2e) #restictions justified, remove DISTURBANCE_TYPE_1

structure.PLI.2o <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1 + DISTURBANCE_TYPE_1 +MEAN,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2o)
lrtest(structure.PLI.2o, structure.PLI.2a) #restictions justified, remove DISTURBANCE_TYPE_1

structure.PLI.2p <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1 + Distance,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2p)
lrtest(structure.PLI.2p, structure.PLI.2e) #restictions justified, remove Distance

structure.PLI.2q <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1 + Distance +MEAN,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2q)
lrtest(structure.PLI.2q, structure.PLI.2a) #restictions justified, remove Distance

structure.PLI.2r <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1 + PROJ_AGE_1_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2r)
lrtest(structure.PLI.2r, structure.PLI.2e)

structure.PLI.2s <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1 + PROJ_AGE_1_1 + MEAN,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2s)
lrtest(structure.PLI.2s, structure.PLI.2e)

structure.PLI.2t <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1 + SPECIES_CD_3_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2t)
lrtest(structure.PLI.2t, structure.PLI.2e)

structure.PLI.2u <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1 + SPECIES_PCT_1_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2u)
lrtest(structure.PLI.2u, structure.PLI.2e)

structure.PLI.2v <- glm(PLI.f ~ years_since  + SPECIES_CD_1_1 + CROWN_CLOSURE_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.2v)
lrtest(structure.PLI.2v, structure.PLI.2e)
```

```{r}

structure.PLI.3a <- glm(PLI.f ~ years_since  + BARC.x,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3a)
lrtest(structure.PLI.3a, structure.PLIb)

structure.PLI.3b <- glm(PLI.f ~ years_since  + BARC.x + SPECIES_CD_1_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3b)
lrtest(structure.PLI.3b, structure.PLI.3a)
lrtest(structure.PLI.3b, structure.PLI.2e)

structure.PLI.3c <- glm(PLI.f ~ years_since  + BARC.x + SPECIES_CD_1_1 +
                          SPECIES_CD_2_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3c)
lrtest(structure.PLI.3c, structure.PLI.3b) #restrictions justified

structure.PLI.3d <- glm(PLI.f ~ years_since  + BARC.x + SPECIES_CD_1_1 +
                          PROJ_HEIGHT_1_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3d)
lrtest(structure.PLI.3d, structure.PLI.3b) #restrictions justified

structure.PLI.3e <- glm(PLI.f ~ years_since  + BARC.x + SPECIES_CD_1_1 +
                          DISTANCE_TO_PERIMETER,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3e)
lrtest(structure.PLI.3e, structure.PLI.3b) #restrictions justified

structure.PLI.3f <- glm(PLI.f ~ years_since  + BARC.x + SPECIES_CD_1_1 +
                          PATCH_SIZE_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3f)
lrtest(structure.PLI.3f, structure.PLI.3b) #restrictions justified

structure.PLI.3g <- glm(PLI.f ~ years_since  + BARC.x + SPECIES_CD_1_1 +
                          MEAN,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3g)
lrtest(structure.PLI.3g, structure.PLI.3b) #restrictions justified

structure.PLI.3h <- glm(PLI.f ~ years_since  + BARC.x + SPECIES_CD_1_1 +
                          DISTURBANCE_TYPE_1,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3h)
lrtest(structure.PLI.3h, structure.PLI.3b) #restrictions justified

structure.PLI.3i <- glm(PLI.f ~ years_since  + BARC.x + SPECIES_CD_1_1 +
                          Distance,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3i)
lrtest(structure.PLI.3i, structure.PLI.3b)

structure.PLI.3j <- glm(PLI.f ~ years_since  + BARC.x + SPECIES_CD_1_1 +
                         PROJ_AGE_1_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3j)
lrtest(structure.PLI.3j, structure.PLI.3b)

structure.PLI.3k <- glm(PLI.f ~ years_since  + BARC.x + SPECIES_CD_1_1 +
                         SPECIES_CD_3_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3k)
lrtest(structure.PLI.3k, structure.PLI.3b)

structure.PLI.3l <- glm(PLI.f ~ years_since  + BARC.x + SPECIES_CD_1_1 +
                         SPECIES_PCT_1_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3l)
lrtest(structure.PLI.3l, structure.PLI.3b)

structure.PLI.3m <- glm(PLI.f ~ years_since  + BARC.x + SPECIES_CD_1_1 +
                         CROWN_CLOSURE_1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(structure.PLI.3m)
lrtest(structure.PLI.3m, structure.PLI.3b)




test()


```

```{r}
bin_dis_GIS1$linpred.GLM2a <- predict(structure.PLI.2b) # Estimated logit using the linear part
bin_dis_GIS1$yhat.GLM2a <- fitted(structure.PLI.2b) # Estimated probability using inverse logityhat values
bin_dis_GIS1$resid.GLM2a <- resid(structure.PLI.2b) # the deviances 

# Graph of predicted probabilities ranges for dead versus alive
# Would like the dead=0 (it is alive) trees to have all low predicted prob(dead) 
# and the dead=1 (it is dead) trees to all have high predicted prob (dead). 
par(mfrow=c(1,1),mai=c(1,1,0.6,0.6),cex=0.8)
plot(bin_dis_GIS1$PLI.f,bin_dis_GIS1$yhat.GLM2a,pch=8,
  main="Model 1: Predicted Prob for Seedling Occurrence (PLI)",
  ylab="Predicted Prob(occurrence)", xlab="Seedling (=1) or No seedling(=0) as Recorded")
par(mfrow=c(1,1),mai=c(1,1,1,1),cex=1)
```

```{r}
# GLM1
cutoff <- 0.5 # you can play around with different cutoff values
n <- dim(bin_dis_GIS1)[1]
#bin_dis_GIS1$PLI_count_bin <- as.numeric(levels(bin_dis_GIS1$PLI_count_bin))[bin_dis_GIS1$PLI_count_bin]
obs <- bin_dis_GIS1$PLI_count_bin
pred <- ifelse(bin_dis_GIS1$yhat.GLM2a >= cutoff, 1,0)

bin_dis_GIS1$GLM2a <- ifelse( obs == 1 & (obs - pred) == 0, 1, 0) ; a <- sum(bin_dis_GIS1$GLM2a) # a: true positives
bin_dis_GIS1$GLM2c <- ifelse( obs == 1 & (obs - pred) == 1, 1, 0) ; c <- sum(bin_dis_GIS1$GLM2c) # c: false negative
bin_dis_GIS1$GLM2b <- ifelse( obs == 0 & (obs - pred) == -1, 1, 0) ; b <- sum(bin_dis_GIS1$GLM2b) # b: false positives
bin_dis_GIS1$GLM2d <- ifelse( obs == 0 & (obs - pred) == 0, 1, 0) ; d <- sum(bin_dis_GIS1$GLM2d) # d: true negatives

# general confusion matrix layout
matrix(c("a","c" , "b","d"), nrow=2, ncol=2)
CM.GLM2 <- matrix(c(a,c , b,d), nrow=2, ncol=2)
CM.GLM2



# overall accuracy = (a+d)/n
GLM2.oa <- (a+d)/n
GLM2.sensitivity <- a/(a+c)
GLM2.specificity <- d/(b+d)
kappa.bit <- (a+b)*(a+c)+(c+d)*(d+b)
GLM2.kappa <- (  ((a+d)/n)  - (kappa.bit/n^2) ) / (1- (kappa.bit/n^2) )
GLM2.TSS <- GLM2.sensitivity + GLM2.specificity -1

GLM2.predacc <- c(GLM2.oa, GLM2.sensitivity, GLM2.specificity, GLM2.kappa,GLM2.TSS)

GLM2.auc <-pROC::auc(bin_dis_GIS1$PLI_count_bin,bin_dis_GIS1$yhat.GLM2a)
plot(pROC::roc(bin_dis_GIS1$PLI_count_bin,bin_dis_GIS1$yhat.GLM2a),auc.polygon=T)
```

```