---
title: "PLI_site"
author: "Nat"
date: "2024-09-11"
output: html_document
---

```{r}

bin_dis_GIS1 <- bin_dis_GIS1

bin_dis_GIS1$BEC_Subzone <- factor(bin_dis_GIS1$BEC_Subzone, 
                                                 levels = c("dk", "xm", "dc", "mk", "xc"))
bin_dis_GIS1$BEC_Zone <- factor(bin_dis_GIS1$BEC_Zone,
                                                  levels = c("IDF", "SBPS"))


```

```{r}
site.PLI.null <- glm(PLI.f ~ 1 ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.null)

site.PLI.a <- glm(PLI.f ~ years_since ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.a)
lrtest(site.PLI.a, site.PLI.null)

site.PLI.b <- glm(PLI.f ~ Aspect ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.b)
lrtest(site.PLI.b, site.PLI.null)

site.PLI.c <- glm(PLI.f ~ Beers_aspect ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.c)
lrtest(site.PLI.c, site.PLI.null)

site.PLI.d <- glm(PLI.f ~ Elevation ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.d)
lrtest(site.PLI.d, site.PLI.null)

site.PLI.e <- glm(PLI.f ~ Slope ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.e)
lrtest(site.PLI.e, site.PLI.null)

site.PLI.f <- glm(PLI.f ~ Solar_Radiation ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.f)
lrtest(site.PLI.f, site.PLI.null)

site.PLI.g <- glm(PLI.f ~ TWI ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.g)
lrtest(site.PLI.g, site.PLI.null)

site.PLI.h <- glm(PLI.f ~ BEC_Zone ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.h)
lrtest(site.PLI.h, site.PLI.null)

site.PLI.i <- glm(PLI.f ~ BEC_Subzone ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.i)
lrtest(site.PLI.i, site.PLI.null)

#site.PLI.j <- glm(PLI.f ~ BEC_Variant ,
#    family=binomial(link = "logit"), data=bin_dis_GIS1)
#summary(site.PLI.j)
#lrtest(site.PLI.j, site.PLI.null)
#figure out NAs

site.PLI.k <- glm(PLI.f ~ PARENT_SOILS ,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.k)
lrtest(site.PLI.k, site.PLI.null)

```

```{r}
site.PLI.2a <- glm(PLI.f ~ years_since + BEC_Zone,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2a)
lrtest(site.PLI.2a, site.PLI.a)
anova(site.PLI.a, site.PLI.2a)

site.PLI.2b <- glm(PLI.f ~ years_since + BEC_Subzone + BEC_Zone,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2b)
lrtest(site.PLI.2b, site.PLI.2a)

site.PLI.2c <- glm(PLI.f ~ years_since + BEC_Subzone + PARENT_SOILS,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2c)
lrtest(site.PLI.2c, site.PLI.2a)

site.PLI.2d <- glm(PLI.f ~ years_since + BEC_Subzone + Elevation,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2d)
lrtest(site.PLI.2d, site.PLI.2a)

site.PLI.2e <- glm(PLI.f ~ years_since + BEC_Subzone + Slope,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2e)
lrtest(site.PLI.2e, site.PLI.2a)

site.PLI.2f <- glm(PLI.f ~ years_since + BEC_Subzone + Slope + Aspect,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2f)
lrtest(site.PLI.2f, site.PLI.2e)

site.PLI.2g <- glm(PLI.f ~ years_since + BEC_Subzone + Slope + Solar_Radiation,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2g)
lrtest(site.PLI.2g, site.PLI.2e)

site.PLI.2h <- glm(PLI.f ~ years_since + BEC_Subzone + Slope + TWI,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2h)
lrtest(site.PLI.2h, site.PLI.2e)

site.PLI.2i <- glm(PLI.f ~ years_since + BEC_Subzone + Slope + Beers_aspect,
    family=binomial(link = "logit"), data=bin_dis_GIS1)
summary(site.PLI.2i)
lrtest(site.PLI.2i, site.PLI.2e)
```
# FORGOT THAT I NEED TO REMOVE MS SITES FUCK
# AND THEN REMOVE SOME OF THESE SOIL GROUPS I GUESS
# BUT THEN WHAT SHOULD I DO ABOUT BEC ZONES???????
